export { AdminLayout } from './layouts/Admin'
export { DocumentLayout } from './layouts/Document'
export { RootLayout } from './layouts/Root'
export { Dashboard as DashboardPage, generateMetadata as dashboardMeta } from './pages/Dashboard'
export { Login, generateMetadata as loginMeta } from './pages/Login'
export { RootPage } from './pages/Root'
