export { AdminLayout } from './layouts/Admin/index.js'
export { RootLayout } from './layouts/Root/index.js'
export { Dashboard as DashboardPage } from './views/Dashboard/index.js'
export { Login } from './views/Login/index.js'
export { RootPage } from './views/Root/index.js'
