export default {
  getFields: () => { },
  getField: () => { },
  getData: () => { },
  getSiblingData: () => { },
  getDataByPath: () => undefined,
  getUnflattenedValues: () => { },
  validateForm: () => { },
  createFormData: () => { },
  submit: () => { },
  dispatchFields: () => { },
  setModified: () => { },
  initialState: {},
  reset: 0,
};
