export default ({ dispatchFields }) => ({
  processing: false,
  modified: false,
  submitted: false,
  getFields: () => { },
  getField: () => { },
  getData: () => { },
  getSiblingData: () => { },
  getDataByPath: () => undefined,
  getUnflattenedValues: () => { },
  validateForm: () => { },
  createFormData: () => { },
  submit: () => { },
  dispatchFields,
  setModified: () => { },
});
