name: Setup node and pnpm
description: Configure the Node.js and pnpm versions

env:
  NODE_VERSION: 18.20.2
  PNPM_VERSION: 8.15.7

runs:
  using: composite
  steps:
    # https://github.com/actions/virtual-environments/issues/1187
    - name: tune linux network
      shell: bash
      run: sudo ethtool -K eth0 tx off rx off

    - name: Setup Node@${{ env.NODE_VERSION }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Install pnpm
      uses: pnpm/action-setup@v3
      with:
        version: ${{ env.PNPM_VERSION }}
        run_install: false

    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - name: Setup pnpm cache
      uses: actions/cache@v4
      with:
        path: ${{ env.STORE_PATH }}
        key: pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          pnpm-store-
          pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}

    - shell: bash
      run: pnpm install
