packages:
  - 'packages/*'
  - 'tools/*'
  - 'test'
  - 'templates/blank'
  - 'templates/website'
  - 'templates/ecommerce'

catalog:
  '@types/react': 19.2.1
  '@types/react-dom': 19.2.1
  copyfiles: 2.4.1
  cross-env: 7.0.3
  dotenv: 16.4.7
  drizzle-kit: 0.31.7
  drizzle-orm: 0.44.7
  graphql: ^16.8.1
  mongodb-memory-server: 10.1.4
  react: 19.2.1
  react-dom: 19.2.1
  tsx: 4.20.6
  typescript: 5.7.3
  vitest: 4.0.15

updateNotifier: false
symlink: true
nodeLinker: isolated
hoistWorkspacePackages: false # the default in pnpm v9 is true, but that can break our runtime dependency checks
savePrefix: ''
