packages:
  - 'packages/*'
  - 'tools/*'
  - 'test'
  - 'templates/blank'
  - 'templates/website'
  - 'templates/ecommerce'

updateNotifier: false
symlink: true
nodeLinker: isolated
hoistWorkspacePackages: false # the default in pnpm v9 is true, but that can break our runtime dependency checks
savePrefix: ''
