packages:
  - packages/*
  - tools/*
  - test
  - templates/blank
  - templates/website
  - templates/ecommerce
updateNotifier: false
catalog:
  "@aws-sdk/client-cognito-identity": ^3.614.0
  "@aws-sdk/client-s3": ^3.614.0
  "@aws-sdk/credential-providers": ^3.614.0
  "@aws-sdk/lib-storage": ^3.614.0
  "@aws-sdk/s3-request-presigner": ^3.614.0
  "@azure/abort-controller": ^1.1.0
  "@azure/storage-blob": ^12.11.0
  "@babel/cli": 7.27.2
  "@babel/core": 7.27.3
  "@babel/preset-env": 7.27.2
  "@babel/preset-react": 7.27.1
  "@babel/preset-typescript": 7.27.1
  "@clack/prompts": ^0.7.0
  "@date-fns/tz": 1.2.0
  "@dnd-kit/core": 6.0.8
  "@dnd-kit/sortable": 7.0.2
  "@dnd-kit/utilities": 3.2.2
  "@eslint-react/eslint-plugin": 1.31.0
  "@eslint/eslintrc": ^3.2.0
  "@eslint/js": 9.22.0
  "@faceless-ui/modal": 3.0.0
  "@faceless-ui/scroll-info": 2.0.0
  "@faceless-ui/window-info": 3.0.1
  "@google-cloud/storage": 7.17.2
  "@hyrious/esbuild-plugin-commonjs": 0.2.6
  "@jest/globals": 29.7.0
  "@lexical/clipboard": 0.35.0
  "@lexical/eslint-plugin": 0.35.0
  "@lexical/headless": 0.35.0
  "@lexical/html": 0.35.0
  "@lexical/link": 0.35.0
  "@lexical/list": 0.35.0
  "@lexical/mark": 0.35.0
  "@lexical/react": 0.35.0
  "@lexical/rich-text": 0.35.0
  "@lexical/selection": 0.35.0
  "@lexical/table": 0.35.0
  "@lexical/utils": 0.35.0
  "@libsql/client": 0.14.0
  "@miniflare/d1": 2.14.4
  "@miniflare/shared": 2.14.4
  "@modelcontextprotocol/sdk": ^1.17.2
  "@monaco-editor/react": 4.7.0
  "@next/bundle-analyzer": 15.4.4
  "@opennextjs/cloudflare": 1.9.2
  "@radix-ui/react-accordion": 1.2.11
  "@radix-ui/react-dialog": ^1.1.14
  "@sentry/nextjs": ^8.33.1
  "@sentry/node": ^8.33.1
  "@sentry/react": ^7.77.0
  "@sentry/types": ^8.33.1
  "@sindresorhus/slugify": ^1.1.0
  "@smithy/node-http-handler": 4.0.3
  "@swc-node/register": 1.10.10
  "@swc/cli": 0.7.7
  "@swc/core": 1.11.29
  "@swc/jest": 0.2.38
  "@tailwindcss/container-queries": ^0.1.1
  "@tailwindcss/postcss": 4.0.12
  "@testing-library/react": 16.3.0
  "@types/busboy": 1.5.4
  "@types/eslint": 9.6.1
  "@types/esprima": ^4.0.6
  "@types/find-node-modules": ^2.1.2
  "@types/is-hotkey": ^0.1.10
  "@types/jest": 29.5.12
  "@types/json-schema": 7.0.15
  "@types/jsonwebtoken": ^9.0.7
  "@types/lodash.get": ^4.4.7
  "@types/mongoose-aggregate-paginate-v2": 1.0.12
  "@types/node": 22.15.30
  "@types/nodemailer": 7.0.2
  "@types/pg": 8.10.2
  "@types/prompts": ^2.4.5
  "@types/range-parser": ^1.2.7
  "@types/react": 19.1.12
  "@types/react-dom": 19.1.9
  "@types/semver": ^7.5.3
  "@types/shelljs": 0.8.15
  "@types/to-snake-case": 1.0.0
  "@types/uuid": 10.0.0
  "@types/ws": ^8.5.10
  "@typescript-eslint/parser": 8.26.1
  "@vercel/blob": ^0.22.3
  "@vercel/git-hooks": ^1.0.0
  "@vercel/mcp-adapter": ^1.0.0
  "@vercel/postgres": ^0.9.0
  "@vitejs/plugin-react": 4.5.2
  acorn: 8.12.1
  ajv: 8.17.1
  amazon-cognito-identity-js: ^6.1.2
  arg: ^5.0.0
  autoprefixer: ^10.4.19
  babel-plugin-react-compiler: 19.1.0-rc.3
  babel-plugin-transform-remove-imports: ^1.8.0
  better-sqlite3: 11.10.0
  bson-objectid: 2.0.4
  busboy: ^1.6.0
  changelogen: ^0.5.5
  ci-info: ^4.1.0
  class-variance-authority: ^0.7.0
  comment-json: ^4.2.3
  console-table-printer: 2.12.1
  copyfiles: 2.4.1
  croner: 9.1.0
  cross-env: 7.0.3
  csstype: 3.1.3
  csv-parse: ^5.6.0
  csv-stringify: ^6.5.2
  dataloader: 2.2.3
  deepmerge: 4.3.1
  dequal: 2.0.3
  dotenv: 16.4.7
  drizzle-kit: 0.31.5
  drizzle-orm: 0.44.6
  embla-carousel-auto-scroll: ^8.1.5
  embla-carousel-react: ^8.5.2
  esbuild: 0.25.5
  esbuild-sass-plugin: 3.3.1
  eslint-config-prettier: 10.1.1
  eslint-plugin-import-x: 4.6.1
  eslint-plugin-jest: 28.11.0
  eslint-plugin-jest-dom: 5.5.0
  eslint-plugin-perfectionist: 3.9.1
  eslint-plugin-playwright: 2.2.0
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-compiler: 19.1.0-rc.2
  eslint-plugin-regexp: 2.7.0
  esprima-next: ^6.0.3
  figures: ^6.1.0
  file-type: 19.3.0
  find-node-modules: ^2.1.3
  form-data: 3.0.1
  geist: ^1.3.0
  get-tsconfig: 4.8.1
  globals: 16.0.0
  globby: 11.1.0
  graphql: ^16.8.1
  graphql-http: ^1.22.0
  graphql-playground-html: 1.6.30
  graphql-scalars: 1.22.2
  http-status: 2.1.0
  husky: 9.0.11
  image-size: 2.0.2
  ipaddr.js: 2.2.0
  is-hotkey: 0.2.0
  jose: 5.9.6
  jsdom: 26.1.0
  json-schema-to-typescript: 15.0.3
  json-schema-to-zod: 2.6.1
  jsonwebtoken: 9.0.1
  jsox: 1.2.121
  jwt-decode: 4.0.0
  lexical: 0.35.0
  license-checker: 25.0.1
  lodash.get: ^4.4.2
  md5: 2.3.0
  mdast-util-from-markdown: 2.0.2
  mdast-util-mdx-jsx: 3.1.3
  micromark-extension-mdx-jsx: 3.0.1
  minimist: 1.2.8
  mongodb: 6.16.0
  mongodb-memory-server: 10.1.4
  mongoose: 8.15.1
  mongoose-paginate-v2: 1.8.5
  next-sitemap: ^4.2.3
  next-themes: 0.4.6
  nodemailer: 7.0.9
  object-to-formdata: 4.5.1
  open: ^10.1.0
  p-limit: ^5.0.0
  path-to-regexp: 6.3.0
  pg: 8.16.3
  pino: 9.14.0
  pino-pretty: 13.1.2
  pluralize: 8.0.0
  postcss: ^8.4.38
  prettier-plugin-tailwindcss: ^0.6.11
  prism-react-renderer: ^2.3.1
  prompts: 2.4.2
  qs-esm: 7.0.2
  range-parser: ^1.2.1
  react: 19.1.1
  react-datepicker: 7.6.0
  react-dom: 19.1.1
  react-error-boundary: 4.1.2
  react-image-crop: 10.1.8
  react-select: 5.9.0
  rimraf: 6.0.1
  rollup: 4.52.3
  rollup-plugin-dts: 6.2.3
  sanitize-filename: 1.6.3
  sass: 1.77.4
  scheduler: 0.25.0
  scmp: 2.1.0
  semver: ^7.5.4
  server-only: ^0.0.1
  shelljs: 0.8.5
  slash: 3.0.0
  slate: 0.91.4
  slate-history: 0.86.0
  slate-hyperscript: 0.81.3
  slate-react: 0.92.0
  sonner: ^1.7.2
  sort-package-json: ^2.10.0
  swc-plugin-transform-remove-imports: 4.0.4
  tailwind-merge: ^2.3.0
  tailwindcss-animate: ^1.0.7
  tar: ^7.4.3
  terminal-link: ^2.1.1
  to-snake-case: 1.0.0
  ts-essentials: 10.0.3
  tstyche: 3.5.0
  turbo: ^2.5.4
  typescript: 5.7.3
  typescript-eslint: 8.26.1
  undici: 7.10.0
  uploadthing: 7.3.0
  uuid: 10.0.0
  use-context-selector: 2.0.0
  vite-tsconfig-paths: 5.1.4
  vitest: 3.2.3
  vue: ^3.0.0
  wrangler: ~4.42.0
  ws: ^8.16.0
