/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {
    'localized-category-block': LocalizedCategoryBlock;
  };
  collections: {
    posts: Post;
    pages: Page;
    categories: Category;
    media: Media;
    'versioned-media': VersionedMedia;
    'unique-docs': UniqueDoc;
    'numeric-id-docs': NumericIdDoc;
    'restricted-docs': RestrictedDoc;
    'where-access-docs': WhereAccessDoc;
    'public-docs': PublicDoc;
    'max-versions-docs': MaxVersionsDoc;
    'autosave-docs': AutosaveDoc;
    'localized-docs': LocalizedDoc;
    'nested-docs': NestedDoc;
    'excluded-docs': ExcludedDoc;
    'payload-kv': PayloadKv;
    users: User;
    'payload-jobs': PayloadJob;
    'payload-branches': PayloadBranch;
    'payload-branch-changes': PayloadBranchChange;
    'payload-branch-merges': PayloadBranchMerge;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    categories: {
      pages: 'pages';
      posts: 'posts';
      content: 'posts' | 'pages';
    };
  };
  collectionsSelect: {
    posts: PostsSelect<false> | PostsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'versioned-media': VersionedMediaSelect<false> | VersionedMediaSelect<true>;
    'unique-docs': UniqueDocsSelect<false> | UniqueDocsSelect<true>;
    'numeric-id-docs': NumericIdDocsSelect<false> | NumericIdDocsSelect<true>;
    'restricted-docs': RestrictedDocsSelect<false> | RestrictedDocsSelect<true>;
    'where-access-docs': WhereAccessDocsSelect<false> | WhereAccessDocsSelect<true>;
    'public-docs': PublicDocsSelect<false> | PublicDocsSelect<true>;
    'max-versions-docs': MaxVersionsDocsSelect<false> | MaxVersionsDocsSelect<true>;
    'autosave-docs': AutosaveDocsSelect<false> | AutosaveDocsSelect<true>;
    'localized-docs': LocalizedDocsSelect<false> | LocalizedDocsSelect<true>;
    'nested-docs': NestedDocsSelect<false> | NestedDocsSelect<true>;
    'excluded-docs': ExcludedDocsSelect<false> | ExcludedDocsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-branches': PayloadBranchesSelect<false> | PayloadBranchesSelect<true>;
    'payload-branch-changes': PayloadBranchChangesSelect<false> | PayloadBranchChangesSelect<true>;
    'payload-branch-merges': PayloadBranchMergesSelect<false> | PayloadBranchMergesSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'es') | ('en' | 'es')[];
  globals: {
    header: Header;
    homepage: Homepage;
    'uninitialized-global': UninitializedGlobal;
    'payload-jobs-stats': PayloadJobsStat;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    'uninitialized-global': UninitializedGlobalSelect<false> | UninitializedGlobalSelect<true>;
    'payload-jobs-stats': PayloadJobsStatsSelect<false> | PayloadJobsStatsSelect<true>;
  };
  locale: 'en' | 'es';
  widgets: {
    welcome: WelcomeWidget;
    collections: CollectionsWidget;
    'collection-query': CollectionQueryWidget;
    activity: ActivityWidget;
    'upload-dropzone': UploadDropzoneWidget;
  };
  user: User;
  jobs: {
    tasks: {
      scheduleMerge: TaskScheduleMerge;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LocalizedCategoryBlock".
 */
export interface LocalizedCategoryBlock {
  category?: (string | null) | Category;
  id?: string | null;
  blockName?: string | null;
  blockType: 'localized-category-block';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  name?: string | null;
  pages?: {
    docs?: (string | Page)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  posts?: {
    docs?: (string | Post)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  content?: {
    docs?: (
      | {
          relationTo?: 'posts';
          value: string | Post;
        }
      | {
          relationTo?: 'pages';
          value: string | Page;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  _branch: string;
  _branchDocID?: (string | null) | Category;
  createdBy?: {
    relationTo: 'users';
    value: string | User;
  } | null;
  updatedBy?: {
    relationTo: 'users';
    value: string | User;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title?: string | null;
  category?: (string | null) | Category;
  _branch: string;
  _branchDocID?: (string | null) | Page;
  createdBy?: {
    relationTo: 'users';
    value: string | User;
  } | null;
  updatedBy?: {
    relationTo: 'users';
    value: string | User;
  } | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  createdBy?: {
    relationTo: 'users';
    value: string | User;
  } | null;
  updatedBy?: {
    relationTo: 'users';
    value: string | User;
  } | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: string;
  title?: string | null;
  order?: number | null;
  confidential?: string | null;
  computedDefault?: string | null;
  internalNote?: string | null;
  category?: (string | null) | Category;
  localizedCategory?: (string | null) | Category;
  sharedLayout?: LocalizedCategoryBlock[] | null;
  _branch: string;
  _branchDocID?: (string | null) | Post;
  createdBy?: {
    relationTo: 'users';
    value: string | User;
  } | null;
  updatedBy?: {
    relationTo: 'users';
    value: string | User;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt?: string | null;
  _branch: string;
  _branchDocID?: (string | null) | Media;
  createdBy?: {
    relationTo: 'users';
    value: string | User;
  } | null;
  updatedBy?: {
    relationTo: 'users';
    value: string | User;
  } | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  variants?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "versioned-media".
 */
export interface VersionedMedia {
  id: string;
  alt?: string | null;
  _branch: string;
  _branchDocID?: (string | null) | VersionedMedia;
  createdBy?: {
    relationTo: 'users';
    value: string | User;
  } | null;
  updatedBy?: {
    relationTo: 'users';
    value: string | User;
  } | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "unique-docs".
 */
export interface UniqueDoc {
  id: string;
  slug?: string | null;
  localizedSlug?: string | null;
  metadata?: {
    code?: string | null;
  };
  site?: string | null;
  customSlug?: string | null;
  _branch: string;
  _branchDocID?: (string | null) | UniqueDoc;
  createdBy?: {
    relationTo: 'users';
    value: string | User;
  } | null;
  updatedBy?: {
    relationTo: 'users';
    value: string | User;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "numeric-id-docs".
 */
export interface NumericIdDoc {
  id: number;
  title?: string | null;
  _branch: string;
  _branchDocID?: (number | null) | NumericIdDoc;
  createdBy?: {
    relationTo: 'users';
    value: string | User;
  } | null;
  updatedBy?: {
    relationTo: 'users';
    value: string | User;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "restricted-docs".
 */
export interface RestrictedDoc {
  id: string;
  title?: string | null;
  _branch: string;
  _branchDocID?: (string | null) | RestrictedDoc;
  createdBy?: {
    relationTo: 'users';
    value: string | User;
  } | null;
  updatedBy?: {
    relationTo: 'users';
    value: string | User;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "where-access-docs".
 */
export interface WhereAccessDoc {
  id: string;
  title?: string | null;
  mergeable?: boolean | null;
  _branch: string;
  _branchDocID?: (string | null) | WhereAccessDoc;
  createdBy?: {
    relationTo: 'users';
    value: string | User;
  } | null;
  updatedBy?: {
    relationTo: 'users';
    value: string | User;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "public-docs".
 */
export interface PublicDoc {
  id: string;
  title?: string | null;
  _branch: string;
  _branchDocID?: (string | null) | PublicDoc;
  createdBy?: {
    relationTo: 'users';
    value: string | User;
  } | null;
  updatedBy?: {
    relationTo: 'users';
    value: string | User;
  } | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "max-versions-docs".
 */
export interface MaxVersionsDoc {
  id: string;
  title?: string | null;
  _branch: string;
  _branchDocID?: (string | null) | MaxVersionsDoc;
  createdBy?: {
    relationTo: 'users';
    value: string | User;
  } | null;
  updatedBy?: {
    relationTo: 'users';
    value: string | User;
  } | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "autosave-docs".
 */
export interface AutosaveDoc {
  id: string;
  title?: string | null;
  _branch: string;
  _branchDocID?: (string | null) | AutosaveDoc;
  createdBy?: {
    relationTo: 'users';
    value: string | User;
  } | null;
  updatedBy?: {
    relationTo: 'users';
    value: string | User;
  } | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "localized-docs".
 */
export interface LocalizedDoc {
  id: string;
  title?: string | null;
  restrictedHidden?: string | null;
  restrictedSelectedOut?: string | null;
  items?:
    | {
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  mergeGuardCategory?: (string | null) | Category;
  computedDefault?: string | null;
  shared?: string | null;
  _branch: string;
  _branchDocID?: (string | null) | LocalizedDoc;
  createdBy?: {
    relationTo: 'users';
    value: string | User;
  } | null;
  updatedBy?: {
    relationTo: 'users';
    value: string | User;
  } | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nested-docs".
 */
export interface NestedDoc {
  id: string;
  title?: string | null;
  metadata?: {
    score: number;
  } | null;
  unstructuredMetadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  items?:
    | {
        label?: string | null;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  layout?: Hero[] | null;
  _branch: string;
  _branchDocID?: (string | null) | NestedDoc;
  createdBy?: {
    relationTo: 'users';
    value: string | User;
  } | null;
  updatedBy?: {
    relationTo: 'users';
    value: string | User;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Hero".
 */
export interface Hero {
  heading?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "excluded-docs".
 */
export interface ExcludedDoc {
  id: string;
  title?: string | null;
  createdBy?: {
    relationTo: 'users';
    value: string | User;
  } | null;
  updatedBy?: {
    relationTo: 'users';
    value: string | User;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: string;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'scheduleMerge';
        taskID: string;
        input:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        parent?: {
          taskSlug?: ('inline' | 'scheduleMerge') | null;
          taskID?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'scheduleMerge') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processingUntil?: string | null;
  processingToken?: string | null;
  /**
   * Used for concurrency control. Jobs with the same key are subject to exclusive/supersedes rules.
   */
  concurrencyKey?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-branches".
 */
export interface PayloadBranch {
  id: string;
  name: string;
  description?: string | null;
  slug: string;
  status?: ('open' | 'merging' | 'merged' | 'closed') | null;
  mergedAt?: string | null;
  mergeProgress?: string | null;
  createdBy?: {
    relationTo: 'users';
    value: string | User;
  } | null;
  updatedBy?: {
    relationTo: 'users';
    value: string | User;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-branch-changes".
 */
export interface PayloadBranchChange {
  id: string;
  branch: string;
  entityType?: ('collection' | 'global') | null;
  collectionSlug?: string | null;
  documentID?: string | null;
  globalSlug?: string | null;
  doc?:
    | ({
        relationTo: 'posts';
        value: string | Post;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'versioned-media';
        value: string | VersionedMedia;
      } | null)
    | ({
        relationTo: 'unique-docs';
        value: string | UniqueDoc;
      } | null)
    | ({
        relationTo: 'numeric-id-docs';
        value: number | NumericIdDoc;
      } | null)
    | ({
        relationTo: 'restricted-docs';
        value: string | RestrictedDoc;
      } | null)
    | ({
        relationTo: 'where-access-docs';
        value: string | WhereAccessDoc;
      } | null)
    | ({
        relationTo: 'public-docs';
        value: string | PublicDoc;
      } | null)
    | ({
        relationTo: 'max-versions-docs';
        value: string | MaxVersionsDoc;
      } | null)
    | ({
        relationTo: 'autosave-docs';
        value: string | AutosaveDoc;
      } | null)
    | ({
        relationTo: 'localized-docs';
        value: string | LocalizedDoc;
      } | null)
    | ({
        relationTo: 'nested-docs';
        value: string | NestedDoc;
      } | null);
  operation: 'create' | 'update' | 'delete';
  baseUpdatedAt?: string | null;
  baseVersionID?: string | null;
  baseVersionUpdatedAt?: string | null;
  createdBy?: {
    relationTo: 'users';
    value: string | User;
  } | null;
  updatedBy?: {
    relationTo: 'users';
    value: string | User;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-branch-merges".
 */
export interface PayloadBranchMerge {
  id: string;
  branch: string;
  mergedAt?: string | null;
  startedAt?: string | null;
  completedAt?: string | null;
  targetBranch?: string | null;
  status?: ('inProgress' | 'awaitingCommit' | 'succeeded' | 'failed' | 'cleanupFailed') | null;
  error?: string | null;
  mergedByCollection?: string | null;
  mergedByID?: string | null;
  mergedByLabel?: string | null;
  changes?:
    | {
        changeID?: string | null;
        collectionSlug?: string | null;
        docID?: string | null;
        docTitle?: string | null;
        globalSlug?: string | null;
        operation?: ('create' | 'update' | 'delete') | null;
        applicationOutcome?:
          | ('unattempted' | 'attempted' | 'applied' | 'committed' | 'failed' | 'rolledBack' | 'unknown')
          | null;
        recoveryOutcome?:
          | ('notNeeded' | 'pending' | 'restored' | 'deleted' | 'unavailable' | 'failed' | 'unknown')
          | null;
        cleanupOutcome?: ('pending' | 'completed' | 'failed' | 'notNeeded' | 'superseded' | 'unknown') | null;
        targetID?: string | null;
        sourceID?: string | null;
        sourceRevision?: string | null;
        sourceUpdatedAt?: string | null;
        sourceVersionIDs?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        beforeVersionID?: string | null;
        afterVersionID?: string | null;
        error?: string | null;
        recoveryError?: string | null;
        cleanupError?: string | null;
        before?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        after?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  createdBy?: {
    relationTo: 'users';
    value: string | User;
  } | null;
  updatedBy?: {
    relationTo: 'users';
    value: string | User;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'posts';
        value: string | Post;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'versioned-media';
        value: string | VersionedMedia;
      } | null)
    | ({
        relationTo: 'unique-docs';
        value: string | UniqueDoc;
      } | null)
    | ({
        relationTo: 'numeric-id-docs';
        value: number | NumericIdDoc;
      } | null)
    | ({
        relationTo: 'restricted-docs';
        value: string | RestrictedDoc;
      } | null)
    | ({
        relationTo: 'where-access-docs';
        value: string | WhereAccessDoc;
      } | null)
    | ({
        relationTo: 'public-docs';
        value: string | PublicDoc;
      } | null)
    | ({
        relationTo: 'max-versions-docs';
        value: string | MaxVersionsDoc;
      } | null)
    | ({
        relationTo: 'autosave-docs';
        value: string | AutosaveDoc;
      } | null)
    | ({
        relationTo: 'localized-docs';
        value: string | LocalizedDoc;
      } | null)
    | ({
        relationTo: 'nested-docs';
        value: string | NestedDoc;
      } | null)
    | ({
        relationTo: 'excluded-docs';
        value: string | ExcludedDoc;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  order?: T;
  confidential?: T;
  computedDefault?: T;
  internalNote?: T;
  category?: T;
  localizedCategory?: T;
  sharedLayout?: T | {};
  _branch?: T;
  _branchDocID?: T;
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  category?: T;
  _branch?: T;
  _branchDocID?: T;
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  pages?: T;
  posts?: T;
  content?: T;
  _branch?: T;
  _branchDocID?: T;
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  _branch?: T;
  _branchDocID?: T;
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  variants?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "versioned-media_select".
 */
export interface VersionedMediaSelect<T extends boolean = true> {
  alt?: T;
  _branch?: T;
  _branchDocID?: T;
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "unique-docs_select".
 */
export interface UniqueDocsSelect<T extends boolean = true> {
  slug?: T;
  localizedSlug?: T;
  metadata?:
    | T
    | {
        code?: T;
      };
  site?: T;
  customSlug?: T;
  _branch?: T;
  _branchDocID?: T;
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "numeric-id-docs_select".
 */
export interface NumericIdDocsSelect<T extends boolean = true> {
  id?: T;
  title?: T;
  _branch?: T;
  _branchDocID?: T;
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "restricted-docs_select".
 */
export interface RestrictedDocsSelect<T extends boolean = true> {
  title?: T;
  _branch?: T;
  _branchDocID?: T;
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "where-access-docs_select".
 */
export interface WhereAccessDocsSelect<T extends boolean = true> {
  title?: T;
  mergeable?: T;
  _branch?: T;
  _branchDocID?: T;
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "public-docs_select".
 */
export interface PublicDocsSelect<T extends boolean = true> {
  title?: T;
  _branch?: T;
  _branchDocID?: T;
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "max-versions-docs_select".
 */
export interface MaxVersionsDocsSelect<T extends boolean = true> {
  title?: T;
  _branch?: T;
  _branchDocID?: T;
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "autosave-docs_select".
 */
export interface AutosaveDocsSelect<T extends boolean = true> {
  title?: T;
  _branch?: T;
  _branchDocID?: T;
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "localized-docs_select".
 */
export interface LocalizedDocsSelect<T extends boolean = true> {
  title?: T;
  restrictedHidden?: T;
  restrictedSelectedOut?: T;
  items?:
    | T
    | {
        label?: T;
        id?: T;
      };
  mergeGuardCategory?: T;
  computedDefault?: T;
  shared?: T;
  _branch?: T;
  _branchDocID?: T;
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nested-docs_select".
 */
export interface NestedDocsSelect<T extends boolean = true> {
  title?: T;
  metadata?: T;
  unstructuredMetadata?: T;
  items?:
    | T
    | {
        label?: T;
        note?: T;
        id?: T;
      };
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              heading?: T;
              id?: T;
              blockName?: T;
            };
      };
  _branch?: T;
  _branchDocID?: T;
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "excluded-docs_select".
 */
export interface ExcludedDocsSelect<T extends boolean = true> {
  title?: T;
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  meta?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        parent?:
          | T
          | {
              taskSlug?: T;
              taskID?: T;
            };
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processingUntil?: T;
  processingToken?: T;
  concurrencyKey?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-branches_select".
 */
export interface PayloadBranchesSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  slug?: T;
  status?: T;
  mergedAt?: T;
  mergeProgress?: T;
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-branch-changes_select".
 */
export interface PayloadBranchChangesSelect<T extends boolean = true> {
  branch?: T;
  entityType?: T;
  collectionSlug?: T;
  documentID?: T;
  globalSlug?: T;
  doc?: T;
  operation?: T;
  baseUpdatedAt?: T;
  baseVersionID?: T;
  baseVersionUpdatedAt?: T;
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-branch-merges_select".
 */
export interface PayloadBranchMergesSelect<T extends boolean = true> {
  branch?: T;
  mergedAt?: T;
  startedAt?: T;
  completedAt?: T;
  targetBranch?: T;
  status?: T;
  error?: T;
  mergedByCollection?: T;
  mergedByID?: T;
  mergedByLabel?: T;
  changes?:
    | T
    | {
        changeID?: T;
        collectionSlug?: T;
        docID?: T;
        docTitle?: T;
        globalSlug?: T;
        operation?: T;
        applicationOutcome?: T;
        recoveryOutcome?: T;
        cleanupOutcome?: T;
        targetID?: T;
        sourceID?: T;
        sourceRevision?: T;
        sourceUpdatedAt?: T;
        sourceVersionIDs?: T;
        beforeVersionID?: T;
        afterVersionID?: T;
        error?: T;
        recoveryError?: T;
        cleanupError?: T;
        before?: T;
        after?: T;
        id?: T;
      };
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: string;
  navLabel?: string | null;
  secondaryLabel?: string | null;
  navItems?:
    | {
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  navigationBlocks?: NavigationBlock[] | null;
  _branch: string;
  createdBy?: {
    relationTo: 'users';
    value: string | User;
  } | null;
  updatedBy?: {
    relationTo: 'users';
    value: string | User;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NavigationBlock".
 */
export interface NavigationBlock {
  label?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'navigation-block';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: string;
  heroTitle?: string | null;
  localizedTitle?: string | null;
  mergeGuardCategory?: (string | null) | Category;
  _branch: string;
  createdBy?: {
    relationTo: 'users';
    value: string | User;
  } | null;
  updatedBy?: {
    relationTo: 'users';
    value: string | User;
  } | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "uninitialized-global".
 */
export interface UninitializedGlobal {
  id: string;
  branchValue?: string | null;
  _branch: string;
  createdBy?: {
    relationTo: 'users';
    value: string | User;
  } | null;
  updatedBy?: {
    relationTo: 'users';
    value: string | User;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats".
 */
export interface PayloadJobsStat {
  id: string;
  stats?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navLabel?: T;
  secondaryLabel?: T;
  navItems?:
    | T
    | {
        label?: T;
        id?: T;
      };
  navigationBlocks?:
    | T
    | {
        'navigation-block'?:
          | T
          | {
              label?: T;
              id?: T;
              blockName?: T;
            };
      };
  _branch?: T;
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  heroTitle?: T;
  localizedTitle?: T;
  mergeGuardCategory?: T;
  _branch?: T;
  createdBy?: T;
  updatedBy?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "uninitialized-global_select".
 */
export interface UninitializedGlobalSelect<T extends boolean = true> {
  branchValue?: T;
  _branch?: T;
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats_select".
 */
export interface PayloadJobsStatsSelect<T extends boolean = true> {
  stats?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "welcome_widget".
 */
export interface WelcomeWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collection-query_widget".
 */
export interface CollectionQueryWidget {
  data?: {
    title?: string | null;
    relatedCollection:
      | 'posts'
      | 'pages'
      | 'categories'
      | 'media'
      | 'versioned-media'
      | 'unique-docs'
      | 'numeric-id-docs'
      | 'restricted-docs'
      | 'where-access-docs'
      | 'public-docs'
      | 'max-versions-docs'
      | 'autosave-docs'
      | 'localized-docs'
      | 'nested-docs'
      | 'excluded-docs'
      | 'users';
    where?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    sortField?: string | null;
    sortDirection?: ('asc' | 'desc') | null;
    limit?: number | null;
  };
  width: 'x-small' | 'small' | 'medium' | 'large' | 'x-large' | 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activity_widget".
 */
export interface ActivityWidget {
  data?: {
    excludedCollections?:
      | (
          | 'posts'
          | 'pages'
          | 'categories'
          | 'media'
          | 'versioned-media'
          | 'unique-docs'
          | 'numeric-id-docs'
          | 'restricted-docs'
          | 'where-access-docs'
          | 'public-docs'
          | 'max-versions-docs'
          | 'autosave-docs'
          | 'localized-docs'
          | 'nested-docs'
          | 'excluded-docs'
          | 'users'
        )[]
      | null;
  };
  width: 'x-small' | 'small' | 'medium' | 'large' | 'x-large' | 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "upload-dropzone_widget".
 */
export interface UploadDropzoneWidget {
  data?: {
    excludedCollections?: ('media' | 'versioned-media')[] | null;
  };
  width: 'x-small' | 'small' | 'medium' | 'large' | 'x-large' | 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskScheduleMerge".
 */
export interface TaskScheduleMerge {
  input: {
    branch: string;
    changes?: string[] | null;
    closeBranch?: boolean | null;
    user?: {
      relationTo: 'users';
      value: string | User;
    } | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  // @ts-ignore
  export interface GeneratedTypes extends Config {}
}
