export const operatorMap = {
  greater_than_equal: '$gte',
  less_than_equal: '$lte',
  less_than: '$lt',
  greater_than: '$gt',
  in: '$in',
  all: '$all',
  not_in: '$nin',
  not_equals: '$ne',
  exists: '$exists',
  equals: '$eq',
  near: '$near',
  every_in: ['$not', '$elemMatch', '$nin'],
  every_not_in: ['$not', '$elemMatch', '$in'],
  every_equals: ['$not', '$elemMatch', '$ne'],
  every_not_equals: ['$not', '$elemMatch', '$eq'],
};
