/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as PayloadRouteImport } from './app/_payload'
import { Route as FrontendRouteImport } from './app/_frontend'
import { Route as FrontendIndexRouteImport } from './app/_frontend/index'
import { Route as PayloadAdminIndexRouteImport } from './app/_payload/admin.index'
import { Route as PayloadApiSplatRouteImport } from './app/_payload/api.$'
import { Route as PayloadAdminSplatRouteImport } from './app/_payload/admin.$'

const PayloadRoute = PayloadRouteImport.update({
  id: '/_payload',
  getParentRoute: () => rootRouteImport,
} as any)
const FrontendRoute = FrontendRouteImport.update({
  id: '/_frontend',
  getParentRoute: () => rootRouteImport,
} as any)
const FrontendIndexRoute = FrontendIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FrontendRoute,
} as any)
const PayloadAdminIndexRoute = PayloadAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => PayloadRoute,
} as any)
const PayloadApiSplatRoute = PayloadApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => PayloadRoute,
} as any)
const PayloadAdminSplatRoute = PayloadAdminSplatRouteImport.update({
  id: '/admin/$',
  path: '/admin/$',
  getParentRoute: () => PayloadRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof FrontendIndexRoute
  '/admin/$': typeof PayloadAdminSplatRoute
  '/api/$': typeof PayloadApiSplatRoute
  '/admin/': typeof PayloadAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof FrontendIndexRoute
  '/admin/$': typeof PayloadAdminSplatRoute
  '/api/$': typeof PayloadApiSplatRoute
  '/admin': typeof PayloadAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_frontend': typeof FrontendRouteWithChildren
  '/_payload': typeof PayloadRouteWithChildren
  '/_frontend/': typeof FrontendIndexRoute
  '/_payload/admin/$': typeof PayloadAdminSplatRoute
  '/_payload/api/$': typeof PayloadApiSplatRoute
  '/_payload/admin/': typeof PayloadAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin/$' | '/api/$' | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin/$' | '/api/$' | '/admin'
  id:
    | '__root__'
    | '/_frontend'
    | '/_payload'
    | '/_frontend/'
    | '/_payload/admin/$'
    | '/_payload/api/$'
    | '/_payload/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  FrontendRoute: typeof FrontendRouteWithChildren
  PayloadRoute: typeof PayloadRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_payload': {
      id: '/_payload'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PayloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_frontend': {
      id: '/_frontend'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof FrontendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_frontend/': {
      id: '/_frontend/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof FrontendIndexRouteImport
      parentRoute: typeof FrontendRoute
    }
    '/_payload/admin/': {
      id: '/_payload/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof PayloadAdminIndexRouteImport
      parentRoute: typeof PayloadRoute
    }
    '/_payload/api/$': {
      id: '/_payload/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof PayloadApiSplatRouteImport
      parentRoute: typeof PayloadRoute
    }
    '/_payload/admin/$': {
      id: '/_payload/admin/$'
      path: '/admin/$'
      fullPath: '/admin/$'
      preLoaderRoute: typeof PayloadAdminSplatRouteImport
      parentRoute: typeof PayloadRoute
    }
  }
}

interface FrontendRouteChildren {
  FrontendIndexRoute: typeof FrontendIndexRoute
}

const FrontendRouteChildren: FrontendRouteChildren = {
  FrontendIndexRoute: FrontendIndexRoute,
}

const FrontendRouteWithChildren = FrontendRoute._addFileChildren(FrontendRouteChildren)

interface PayloadRouteChildren {
  PayloadAdminSplatRoute: typeof PayloadAdminSplatRoute
  PayloadApiSplatRoute: typeof PayloadApiSplatRoute
  PayloadAdminIndexRoute: typeof PayloadAdminIndexRoute
}

const PayloadRouteChildren: PayloadRouteChildren = {
  PayloadAdminSplatRoute: PayloadAdminSplatRoute,
  PayloadApiSplatRoute: PayloadApiSplatRoute,
  PayloadAdminIndexRoute: PayloadAdminIndexRoute,
}

const PayloadRouteWithChildren = PayloadRoute._addFileChildren(PayloadRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  FrontendRoute: FrontendRouteWithChildren,
  PayloadRoute: PayloadRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
