name: Release Commenter
description: Comment on PRs and Issues when a fix is released
branding:
  icon: message-square
  color: blue
inputs:
  GITHUB_TOKEN:
    description: |
      A GitHub personal access token with repo scope, such as
      secrets.GITHUB_TOKEN.
    required: true
  comment-template:
    description: |
      Text template for the comment string.
    required: false
    default: |
      Included in release {release_link}
  label-template:
    description: Add the given label. Multiple labels can be separated by commas.
    required: false
  skip-label:
    description: Skip commenting if any of the given label are present. Multiple labels can be separated by commas.
    required: false
    default: 'dependencies'
  tag-filter:
    description: |
      Filter tags by a regular expression. Must be escaped. e.g. 'v\\d' to isolate tags between major versions.
    required: false
    default: null
runs:
  using: node20
  main: dist/index.js
