export const firstArrayText = 'first-array-text'
export const secondArrayText = 'second-array-text'

export const slug = 'posts'
export const unrestrictedSlug = 'unrestricted'
export const readOnlySlug = 'read-only-collection'

export const userRestrictedSlug = 'user-restricted'
export const restrictedSlug = 'restricted'
export const restrictedVersionsSlug = 'restricted-versions'
export const siblingDataSlug = 'sibling-data'
export const relyOnRequestHeadersSlug = 'rely-on-request-headers'
export const docLevelAccessSlug = 'doc-level-access'
export const hiddenFieldsSlug = 'hidden-fields'
export const hiddenAccessCountSlug = 'hidden-access-count'
export const hiddenAccessSlug = 'hidden-access'
