export { getSubViewActions, getViewActions } from './attachViewActions.js'
export { getCustomViewByKey } from './getCustomViewByKey.js'
export { getCustomViewByRoute } from './getCustomViewByRoute.js'
export { getDocumentViewInfo } from './getDocumentViewInfo.js'
export { isPathMatchingRoute } from './isPathMatchingRoute.js'
export type { ViewFromConfig } from './types.js'
