/* THIS FILE WAS GENERATED AUTOMATICALLY BY PAYLOAD. */
/* DO NOT MODIFY IT BECAUSE IT COULD BE REWRITTEN AT ANY TIME. */
import Root from '@payloadcms/next/pages/Root'
import configPromise from 'payload-config'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const config = await configPromise
  return <Root config={config}>{children}</Root>
}
