export const categoriesSlug = 'categories'
export const departmentsSlug = 'departments'
export const foldersSlug = 'folders'
export const organizationsSlug = 'organizations'
export const pagesSlug = 'pages'
export const productsSlug = 'products'
export const regionsSlug = 'regions'
