import type { PayloadRequest } from '../../types/index.js'

const serverGeneratedAPIKeyRequests = new WeakSet<PayloadRequest>()

/** Returns whether the request is assigning an API key generated by Payload. */
export const isServerGeneratedAPIKeyRequest = (req: PayloadRequest): boolean =>
  serverGeneratedAPIKeyRequests.has(req)

/** Allows API key assignment while Payload persists a server-generated key. */
export const withServerGeneratedAPIKey = async <T>(
  req: PayloadRequest,
  callback: () => Promise<T>,
): Promise<T> => {
  serverGeneratedAPIKeyRequests.add(req)

  try {
    return await callback()
  } finally {
    serverGeneratedAPIKeyRequests.delete(req)
  }
}
