export const tableJson = {
  children: [
    {
      children: [
        {
          children: [
            {
              children: [
                {
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                  text: ' Option            ',
                  type: 'text',
                  version: 1,
                },
              ],
              direction: null,
              format: '',
              indent: 0,
              type: 'paragraph',
              version: 1,
              textFormat: 0,
              textStyle: '',
            },
          ],
          direction: null,
          format: '',
          indent: 0,
          type: 'tablecell',
          version: 1,
          backgroundColor: null,
          colSpan: 1,
          headerState: 1,
          rowSpan: 1,
        },
        {
          children: [
            {
              children: [
                {
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                  text: ' Default route           ',
                  type: 'text',
                  version: 1,
                },
              ],
              direction: null,
              format: '',
              indent: 0,
              type: 'paragraph',
              version: 1,
              textFormat: 0,
              textStyle: '',
            },
          ],
          direction: null,
          format: '',
          indent: 0,
          type: 'tablecell',
          version: 1,
          backgroundColor: null,
          colSpan: 1,
          headerState: 1,
          rowSpan: 1,
        },
        {
          children: [
            {
              children: [
                {
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                  text: ' Description                                     ',
                  type: 'text',
                  version: 1,
                },
              ],
              direction: null,
              format: '',
              indent: 0,
              type: 'paragraph',
              version: 1,
              textFormat: 0,
              textStyle: '',
            },
          ],
          direction: null,
          format: '',
          indent: 0,
          type: 'tablecell',
          version: 1,
          backgroundColor: null,
          colSpan: 1,
          headerState: 1,
          rowSpan: 1,
        },
      ],
      direction: null,
      format: '',
      indent: 0,
      type: 'tablerow',
      version: 1,
    },
    {
      children: [
        {
          children: [
            {
              children: [
                {
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                  text: ' ',
                  type: 'text',
                  version: 1,
                },
                {
                  detail: 0,
                  format: 16,
                  mode: 'normal',
                  style: '',
                  text: 'account',
                  type: 'text',
                  version: 1,
                },
                {
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                  text: ' *         ',
                  type: 'text',
                  version: 1,
                },
              ],
              direction: null,
              format: '',
              indent: 0,
              type: 'paragraph',
              version: 1,
              textFormat: 0,
              textStyle: '',
            },
          ],
          direction: null,
          format: '',
          indent: 0,
          type: 'tablecell',
          version: 1,
          backgroundColor: null,
          colSpan: 1,
          headerState: 0,
          rowSpan: 1,
        },
        {
          children: [
            {
              children: [
                {
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                  text: '                         ',
                  type: 'text',
                  version: 1,
                },
              ],
              direction: null,
              format: '',
              indent: 0,
              type: 'paragraph',
              version: 1,
              textFormat: 0,
              textStyle: '',
            },
          ],
          direction: null,
          format: '',
          indent: 0,
          type: 'tablecell',
          version: 1,
          backgroundColor: null,
          colSpan: 1,
          headerState: 0,
          rowSpan: 1,
        },
        {
          children: [
            {
              children: [
                {
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                  text: " The user's account page.                        ",
                  type: 'text',
                  version: 1,
                },
              ],
              direction: null,
              format: '',
              indent: 0,
              type: 'paragraph',
              version: 1,
              textFormat: 0,
              textStyle: '',
            },
          ],
          direction: null,
          format: '',
          indent: 0,
          type: 'tablecell',
          version: 1,
          backgroundColor: null,
          colSpan: 1,
          headerState: 0,
          rowSpan: 1,
        },
      ],
      direction: null,
      format: '',
      indent: 0,
      type: 'tablerow',
      version: 1,
    },
    {
      children: [
        {
          children: [
            {
              children: [
                {
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                  text: ' ',
                  type: 'text',
                  version: 1,
                },
                {
                  detail: 0,
                  format: 16,
                  mode: 'normal',
                  style: '',
                  text: 'createFirstUser',
                  type: 'text',
                  version: 1,
                },
                {
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                  text: ' ',
                  type: 'text',
                  version: 1,
                },
              ],
              direction: null,
              format: '',
              indent: 0,
              type: 'paragraph',
              version: 1,
              textFormat: 0,
              textStyle: '',
            },
          ],
          direction: null,
          format: '',
          indent: 0,
          type: 'tablecell',
          version: 1,
          backgroundColor: null,
          colSpan: 1,
          headerState: 0,
          rowSpan: 1,
        },
        {
          children: [
            {
              children: [
                {
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                  text: ' ',
                  type: 'text',
                  version: 1,
                },
                {
                  detail: 0,
                  format: 16,
                  mode: 'normal',
                  style: '',
                  text: '/create-first-user',
                  type: 'text',
                  version: 1,
                },
                {
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                  text: '    ',
                  type: 'text',
                  version: 1,
                },
              ],
              direction: null,
              format: '',
              indent: 0,
              type: 'paragraph',
              version: 1,
              textFormat: 0,
              textStyle: '',
            },
          ],
          direction: null,
          format: '',
          indent: 0,
          type: 'tablecell',
          version: 1,
          backgroundColor: null,
          colSpan: 1,
          headerState: 0,
          rowSpan: 1,
        },
        {
          children: [
            {
              children: [
                {
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                  text: ' The page to create the first user.              ',
                  type: 'text',
                  version: 1,
                },
              ],
              direction: null,
              format: '',
              indent: 0,
              type: 'paragraph',
              version: 1,
              textFormat: 0,
              textStyle: '',
            },
          ],
          direction: null,
          format: '',
          indent: 0,
          type: 'tablecell',
          version: 1,
          backgroundColor: null,
          colSpan: 1,
          headerState: 0,
          rowSpan: 1,
        },
      ],
      direction: null,
      format: '',
      indent: 0,
      type: 'tablerow',
      version: 1,
    },
  ],
  direction: null,
  format: '',
  indent: 0,
  type: 'table',
  version: 1,
}
