import type { Category, Media, Product, VariantOption, VariantType } from '@/payload-types'
import { RequiredDataFromCollectionSlug } from 'payload'

type ProductArgs = {
  galleryImages: NonNullable<Product['gallery']>
  metaImage: Media
  contentImage: Media
  variantTypes: VariantType[]
  categories: Category[]
  relatedProducts: Product[]
}

export const productTshirtData: (
  args: ProductArgs,
) => RequiredDataFromCollectionSlug<'products'> = ({
  galleryImages,
  relatedProducts,
  metaImage,
  contentImage,
  variantTypes,
  categories,
}) => {
  return {
    enableVariants: true,
    variantTypes: variantTypes,
    inventory: 0,
    meta: {
      title: 'Tshirt | Payload Ecommerce Template',
      image: metaImage,
      description:
        'Top off your look with our classic Tshirt, crafted for style and comfort. Made with breathable, high-quality materials and an adjustable strap for the perfect fit.',
    },
    _status: 'published',
    layout: [
      {
        blockType: 'mediaBlock',
        media: contentImage,
      },
      {
        blockType: 'content',
        columns: [
          {
            size: 'half',
            richText: {
              root: {
                children: [
                  {
                    children: [
                      {
                        children: [
                          {
                            detail: 0,
                            format: 0,
                            mode: 'normal',
                            style: '',
                            text: 'This is 100% cotton unisex fitted tee with screen printed design. Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document',
                            type: 'text',
                            version: 1,
                          },
                          {
                            type: 'linebreak',
                            version: 1,
                          },
                        ],
                        direction: 'ltr',
                        format: 'left',
                        indent: 0,
                        type: 'listitem',
                        version: 1,
                        value: 1,
                      },
                      {
                        children: [
                          {
                            children: [
                              {
                                children: [
                                  {
                                    detail: 0,
                                    format: 0,
                                    mode: 'normal',
                                    style: '',
                                    text: 'Product Type: t-shirt',
                                    type: 'text',
                                    version: 1,
                                  },
                                ],
                                direction: 'ltr',
                                format: '',
                                indent: 1,
                                type: 'listitem',
                                version: 1,
                                value: 1,
                              },
                              {
                                children: [
                                  {
                                    detail: 0,
                                    format: 0,
                                    mode: 'normal',
                                    style: '',
                                    text: 'Material: 100% cotton',
                                    type: 'text',
                                    version: 1,
                                  },
                                ],
                                direction: 'ltr',
                                format: '',
                                indent: 1,
                                type: 'listitem',
                                version: 1,
                                value: 2,
                              },
                              {
                                children: [
                                  {
                                    detail: 0,
                                    format: 0,
                                    mode: 'normal',
                                    style: '',
                                    text: 'Colour: black',
                                    type: 'text',
                                    version: 1,
                                  },
                                ],
                                direction: 'ltr',
                                format: '',
                                indent: 1,
                                type: 'listitem',
                                version: 1,
                                value: 3,
                              },
                              {
                                children: [
                                  {
                                    detail: 0,
                                    format: 0,
                                    mode: 'normal',
                                    style: '',
                                    text: 'Style: men (unisex)',
                                    type: 'text',
                                    version: 1,
                                  },
                                ],
                                direction: 'ltr',
                                format: '',
                                indent: 1,
                                type: 'listitem',
                                version: 1,
                                value: 4,
                              },
                            ],
                            direction: 'ltr',
                            format: 'left',
                            indent: 0,
                            type: 'list',
                            version: 1,
                            listType: 'bullet',
                            start: 1,
                            tag: 'ul',
                          },
                        ],
                        direction: 'ltr',
                        format: 'left',
                        indent: 0,
                        type: 'listitem',
                        version: 1,
                        value: 2,
                      },
                    ],
                    direction: 'ltr',
                    format: '',
                    indent: 0,
                    type: 'list',
                    version: 1,
                    listType: 'bullet',
                    start: 1,
                    tag: 'ul',
                  },
                ],
                direction: 'ltr',
                format: '',
                indent: 0,
                type: 'root',
                version: 1,
              },
            },
          },
          {
            size: 'half',
            richText: {
              root: {
                children: [
                  {
                    children: [
                      {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: 'Size chart',
                        type: 'text',
                        version: 1,
                      },
                    ],
                    direction: 'ltr',
                    format: '',
                    indent: 0,
                    type: 'paragraph',
                    version: 1,
                    textFormat: 0,
                    textStyle: '',
                  },
                  {
                    children: [
                      {
                        children: [
                          {
                            children: [
                              {
                                children: [
                                  {
                                    detail: 0,
                                    format: 1,
                                    mode: 'normal',
                                    style: '',
                                    text: ' ',
                                    type: 'text',
                                    version: 1,
                                  },
                                ],
                                direction: null,
                                format: 'left',
                                indent: 0,
                                type: 'paragraph',
                                version: 1,
                                textFormat: 1,
                                textStyle: '',
                              },
                            ],
                            direction: null,
                            format: '',
                            indent: 0,
                            type: 'tablecell',
                            version: 1,
                            textFormat: 1,
                            backgroundColor: null,
                            colSpan: 1,
                            headerState: 0,
                            rowSpan: 1,
                            width: 103.531,
                          },
                          {
                            children: [
                              {
                                children: [
                                  {
                                    detail: 0,
                                    format: 1,
                                    mode: 'normal',
                                    style: '',
                                    text: 'length (IN)',
                                    type: 'text',
                                    version: 1,
                                  },
                                ],
                                direction: 'ltr',
                                format: 'left',
                                indent: 0,
                                type: 'paragraph',
                                version: 1,
                                textFormat: 1,
                                textStyle: '',
                              },
                            ],
                            direction: 'ltr',
                            format: '',
                            indent: 0,
                            type: 'tablecell',
                            version: 1,
                            textFormat: 1,
                            backgroundColor: null,
                            colSpan: 1,
                            headerState: 0,
                            rowSpan: 1,
                            width: 103.531,
                          },
                          {
                            children: [
                              {
                                children: [
                                  {
                                    detail: 0,
                                    format: 1,
                                    mode: 'normal',
                                    style: '',
                                    text: 'length (CM)',
                                    type: 'text',
                                    version: 1,
                                  },
                                ],
                                direction: 'ltr',
                                format: 'left',
                                indent: 0,
                                type: 'paragraph',
                                version: 1,
                                textFormat: 1,
                                textStyle: '',
                              },
                            ],
                            direction: 'ltr',
                            format: '',
                            indent: 0,
                            type: 'tablecell',
                            version: 1,
                            textFormat: 1,
                            backgroundColor: null,
                            colSpan: 1,
                            headerState: 0,
                            rowSpan: 1,
                            width: 103.531,
                          },
                          {
                            children: [
                              {
                                children: [
                                  {
                                    detail: 0,
                                    format: 1,
                                    mode: 'normal',
                                    style: '',
                                    text: 'chest (IN)',
                                    type: 'text',
                                    version: 1,
                                  },
                                ],
                                direction: 'ltr',
                                format: 'left',
                                indent: 0,
                                type: 'paragraph',
                                version: 1,
                                textFormat: 1,
                                textStyle: '',
                              },
                            ],
                            direction: 'ltr',
                            format: '',
                            indent: 0,
                            type: 'tablecell',
                            version: 1,
                            textFormat: 1,
                            backgroundColor: null,
                            colSpan: 1,
                            headerState: 0,
                            rowSpan: 1,
                            width: 103.531,
                          },
                          {
                            children: [
                              {
                                children: [
                                  {
                                    detail: 0,
                                    format: 1,
                                    mode: 'normal',
                                    style: '',
                                    text: 'chest (CM)',
                                    type: 'text',
                                    version: 1,
                                  },
                                ],
                                direction: 'ltr',
                                format: 'left',
                                indent: 0,
                                type: 'paragraph',
                                version: 1,
                                textFormat: 1,
                                textStyle: '',
                              },
                            ],
                            direction: 'ltr',
                            format: '',
                            indent: 0,
                            type: 'tablecell',
                            version: 1,
                            textFormat: 1,
                            backgroundColor: null,
                            colSpan: 1,
                            headerState: 0,
                            rowSpan: 1,
                            width: 103.539,
                          },
                        ],
                        direction: 'ltr',
                        format: 'center',
                        indent: 0,
                        type: 'tablerow',
                        version: 1,
                        textFormat: 1,
                      },
                      {
                        children: [
                          {
                            children: [
                              {
                                children: [
                                  {
                                    detail: 0,
                                    format: 0,
                                    mode: 'normal',
                                    style: '',
                                    text: 's',
                                    type: 'text',
                                    version: 1,
                                  },
                                ],
                                direction: 'ltr',
                                format: 'left',
                                indent: 0,
                                type: 'paragraph',
                                version: 1,
                                textFormat: 0,
                                textStyle: '',
                              },
                            ],
                            direction: 'ltr',
                            format: '',
                            indent: 0,
                            type: 'tablecell',
                            version: 1,
                            backgroundColor: null,
                            colSpan: 1,
                            headerState: 0,
                            rowSpan: 1,
                            width: 103.531,
                          },
                          {
                            children: [
                              {
                                children: [
                                  {
                                    detail: 0,
                                    format: 0,
                                    mode: 'normal',
                                    style: '',
                                    text: '26-28',
                                    type: 'text',
                                    version: 1,
                                  },
                                ],
                                direction: null,
                                format: 'left',
                                indent: 0,
                                type: 'paragraph',
                                version: 1,
                                textFormat: 0,
                                textStyle: '',
                              },
                            ],
                            direction: null,
                            format: '',
                            indent: 0,
                            type: 'tablecell',
                            version: 1,
                            backgroundColor: null,
                            colSpan: 1,
                            headerState: 0,
                            rowSpan: 1,
                            width: 103.531,
                          },
                          {
                            children: [
                              {
                                children: [
                                  {
                                    detail: 0,
                                    format: 0,
                                    mode: 'normal',
                                    style: '',
                                    text: '66-68',
                                    type: 'text',
                                    version: 1,
                                  },
                                ],
                                direction: null,
                                format: 'left',
                                indent: 0,
                                type: 'paragraph',
                                version: 1,
                                textFormat: 0,
                                textStyle: '',
                              },
                            ],
                            direction: null,
                            format: '',
                            indent: 0,
                            type: 'tablecell',
                            version: 1,
                            backgroundColor: null,
                            colSpan: 1,
                            headerState: 0,
                            rowSpan: 1,
                            width: 103.531,
                          },
                          {
                            children: [
                              {
                                children: [
                                  {
                                    detail: 0,
                                    format: 0,
                                    mode: 'normal',
                                    style: '',
                                    text: '34-36',
                                    type: 'text',
                                    version: 1,
                                  },
                                ],
                                direction: null,
                                format: 'left',
                                indent: 0,
                                type: 'paragraph',
                                version: 1,
                                textFormat: 0,
                                textStyle: '',
                              },
                            ],
                            direction: null,
                            format: '',
                            indent: 0,
                            type: 'tablecell',
                            version: 1,
                            backgroundColor: null,
                            colSpan: 1,
                            headerState: 0,
                            rowSpan: 1,
                            width: 103.531,
                          },
                          {
                            children: [
                              {
                                children: [
                                  {
                                    detail: 0,
                                    format: 0,
                                    mode: 'normal',
                                    style: '',
                                    text: '86-91',
                                    type: 'text',
                                    version: 1,
                                  },
                                ],
                                direction: null,
                                format: 'left',
                                indent: 0,
                                type: 'paragraph',
                                version: 1,
                                textFormat: 0,
                                textStyle: '',
                              },
                            ],
                            direction: null,
                            format: '',
                            indent: 0,
                            type: 'tablecell',
                            version: 1,
                            backgroundColor: null,
                            colSpan: 1,
                            headerState: 0,
                            rowSpan: 1,
                            width: 103.539,
                          },
                        ],
                        direction: null,
                        format: 'center',
                        indent: 0,
                        type: 'tablerow',
                        version: 1,
                      },
                      {
                        children: [
                          {
                            children: [
                              {
                                children: [
                                  {
                                    detail: 0,
                                    format: 0,
                                    mode: 'normal',
                                    style: '',
                                    text: 'm',
                                    type: 'text',
                                    version: 1,
                                  },
                                ],
                                direction: 'ltr',
                                format: 'left',
                                indent: 0,
                                type: 'paragraph',
                                version: 1,
                                textFormat: 0,
                                textStyle: '',
                              },
                            ],
                            direction: 'ltr',
                            format: '',
                            indent: 0,
                            type: 'tablecell',
                            version: 1,
                            backgroundColor: null,
                            colSpan: 1,
                            headerState: 0,
                            rowSpan: 1,
                            width: 103.531,
                          },
                          {
                            children: [
                              {
                                children: [
                                  {
                                    detail: 0,
                                    format: 0,
                                    mode: 'normal',
                                    style: '',
                                    text: '27-29',
                                    type: 'text',
                                    version: 1,
                                  },
                                ],
                                direction: null,
                                format: 'left',
                                indent: 0,
                                type: 'paragraph',
                                version: 1,
                                textFormat: 0,
                                textStyle: '',
                              },
                            ],
                            direction: null,
                            format: '',
                            indent: 0,
                            type: 'tablecell',
                            version: 1,
                            backgroundColor: null,
                            colSpan: 1,
                            headerState: 0,
                            rowSpan: 1,
                            width: 103.531,
                          },
                          {
                            children: [
                              {
                                children: [
                                  {
                                    detail: 0,
                                    format: 0,
                                    mode: 'normal',
                                    style: '',
                                    text: '70-72',
                                    type: 'text',
                                    version: 1,
                                  },
                                ],
                                direction: null,
                                format: 'left',
                                indent: 0,
                                type: 'paragraph',
                                version: 1,
                                textFormat: 0,
                                textStyle: '',
                              },
                            ],
                            direction: null,
                            format: '',
                            indent: 0,
                            type: 'tablecell',
                            version: 1,
                            backgroundColor: null,
                            colSpan: 1,
                            headerState: 0,
                            rowSpan: 1,
                            width: 103.531,
                          },
                          {
                            children: [
                              {
                                children: [
                                  {
                                    detail: 0,
                                    format: 0,
                                    mode: 'normal',
                                    style: '',
                                    text: '19-21',
                                    type: 'text',
                                    version: 1,
                                  },
                                ],
                                direction: null,
                                format: 'left',
                                indent: 0,
                                type: 'paragraph',
                                version: 1,
                                textFormat: 0,
                                textStyle: '',
                              },
                            ],
                            direction: null,
                            format: '',
                            indent: 0,
                            type: 'tablecell',
                            version: 1,
                            backgroundColor: null,
                            colSpan: 1,
                            headerState: 0,
                            rowSpan: 1,
                            width: 103.531,
                          },
                          {
                            children: [
                              {
                                children: [
                                  {
                                    detail: 0,
                                    format: 0,
                                    mode: 'normal',
                                    style: '',
                                    text: '50-52',
                                    type: 'text',
                                    version: 1,
                                  },
                                ],
                                direction: null,
                                format: 'left',
                                indent: 0,
                                type: 'paragraph',
                                version: 1,
                                textFormat: 0,
                                textStyle: '',
                              },
                            ],
                            direction: null,
                            format: '',
                            indent: 0,
                            type: 'tablecell',
                            version: 1,
                            backgroundColor: null,
                            colSpan: 1,
                            headerState: 0,
                            rowSpan: 1,
                            width: 103.539,
                          },
                        ],
                        direction: null,
                        format: 'center',
                        indent: 0,
                        type: 'tablerow',
                        version: 1,
                      },
                      {
                        children: [
                          {
                            children: [
                              {
                                children: [
                                  {
                                    detail: 0,
                                    format: 0,
                                    mode: 'normal',
                                    style: '',
                                    text: 'l',
                                    type: 'text',
                                    version: 1,
                                  },
                                ],
                                direction: 'ltr',
                                format: 'left',
                                indent: 0,
                                type: 'paragraph',
                                version: 1,
                                textFormat: 0,
                                textStyle: '',
                              },
                            ],
                            direction: 'ltr',
                            format: '',
                            indent: 0,
                            type: 'tablecell',
                            version: 1,
                            backgroundColor: null,
                            colSpan: 1,
                            headerState: 0,
                            rowSpan: 1,
                            width: 103.531,
                          },
                          {
                            children: [
                              {
                                children: [
                                  {
                                    detail: 0,
                                    format: 0,
                                    mode: 'normal',
                                    style: '',
                                    text: '29-31',
                                    type: 'text',
                                    version: 1,
                                  },
                                ],
                                direction: null,
                                format: 'left',
                                indent: 0,
                                type: 'paragraph',
                                version: 1,
                                textFormat: 0,
                                textStyle: '',
                              },
                            ],
                            direction: null,
                            format: '',
                            indent: 0,
                            type: 'tablecell',
                            version: 1,
                            backgroundColor: null,
                            colSpan: 1,
                            headerState: 0,
                            rowSpan: 1,
                            width: 103.531,
                          },
                          {
                            children: [
                              {
                                children: [
                                  {
                                    detail: 0,
                                    format: 0,
                                    mode: 'normal',
                                    style: '',
                                    text: '75-77',
                                    type: 'text',
                                    version: 1,
                                  },
                                ],
                                direction: null,
                                format: 'left',
                                indent: 0,
                                type: 'paragraph',
                                version: 1,
                                textFormat: 0,
                                textStyle: '',
                              },
                            ],
                            direction: null,
                            format: '',
                            indent: 0,
                            type: 'tablecell',
                            version: 1,
                            backgroundColor: null,
                            colSpan: 1,
                            headerState: 0,
                            rowSpan: 1,
                            width: 103.531,
                          },
                          {
                            children: [
                              {
                                children: [
                                  {
                                    detail: 0,
                                    format: 0,
                                    mode: 'normal',
                                    style: '',
                                    text: '21-23',
                                    type: 'text',
                                    version: 1,
                                  },
                                ],
                                direction: null,
                                format: 'left',
                                indent: 0,
                                type: 'paragraph',
                                version: 1,
                                textFormat: 0,
                                textStyle: '',
                              },
                            ],
                            direction: null,
                            format: '',
                            indent: 0,
                            type: 'tablecell',
                            version: 1,
                            backgroundColor: null,
                            colSpan: 1,
                            headerState: 0,
                            rowSpan: 1,
                            width: 103.531,
                          },
                          {
                            children: [
                              {
                                children: [
                                  {
                                    detail: 0,
                                    format: 0,
                                    mode: 'normal',
                                    style: '',
                                    text: '55-57',
                                    type: 'text',
                                    version: 1,
                                  },
                                ],
                                direction: null,
                                format: 'left',
                                indent: 0,
                                type: 'paragraph',
                                version: 1,
                                textFormat: 0,
                                textStyle: '',
                              },
                            ],
                            direction: null,
                            format: '',
                            indent: 0,
                            type: 'tablecell',
                            version: 1,
                            backgroundColor: null,
                            colSpan: 1,
                            headerState: 0,
                            rowSpan: 1,
                            width: 103.539,
                          },
                        ],
                        direction: null,
                        format: 'center',
                        indent: 0,
                        type: 'tablerow',
                        version: 1,
                      },
                      {
                        children: [
                          {
                            children: [
                              {
                                children: [
                                  {
                                    detail: 0,
                                    format: 0,
                                    mode: 'normal',
                                    style: '',
                                    text: 'xl',
                                    type: 'text',
                                    version: 1,
                                  },
                                ],
                                direction: 'ltr',
                                format: 'left',
                                indent: 0,
                                type: 'paragraph',
                                version: 1,
                                textFormat: 0,
                                textStyle: '',
                              },
                            ],
                            direction: 'ltr',
                            format: '',
                            indent: 0,
                            type: 'tablecell',
                            version: 1,
                            backgroundColor: null,
                            colSpan: 1,
                            headerState: 0,
                            rowSpan: 1,
                            width: 103.531,
                          },
                          {
                            children: [
                              {
                                children: [
                                  {
                                    detail: 0,
                                    format: 0,
                                    mode: 'normal',
                                    style: '',
                                    text: '30-32',
                                    type: 'text',
                                    version: 1,
                                  },
                                ],
                                direction: null,
                                format: 'left',
                                indent: 0,
                                type: 'paragraph',
                                version: 1,
                                textFormat: 0,
                                textStyle: '',
                              },
                            ],
                            direction: null,
                            format: '',
                            indent: 0,
                            type: 'tablecell',
                            version: 1,
                            backgroundColor: null,
                            colSpan: 1,
                            headerState: 0,
                            rowSpan: 1,
                            width: 103.531,
                          },
                          {
                            children: [
                              {
                                children: [
                                  {
                                    detail: 0,
                                    format: 0,
                                    mode: 'normal',
                                    style: '',
                                    text: '77-79',
                                    type: 'text',
                                    version: 1,
                                  },
                                ],
                                direction: null,
                                format: 'left',
                                indent: 0,
                                type: 'paragraph',
                                version: 1,
                                textFormat: 0,
                                textStyle: '',
                              },
                            ],
                            direction: null,
                            format: '',
                            indent: 0,
                            type: 'tablecell',
                            version: 1,
                            backgroundColor: null,
                            colSpan: 1,
                            headerState: 0,
                            rowSpan: 1,
                            width: 103.531,
                          },
                          {
                            children: [
                              {
                                children: [
                                  {
                                    detail: 0,
                                    format: 0,
                                    mode: 'normal',
                                    style: '',
                                    text: '23-25',
                                    type: 'text',
                                    version: 1,
                                  },
                                ],
                                direction: null,
                                format: 'left',
                                indent: 0,
                                type: 'paragraph',
                                version: 1,
                                textFormat: 0,
                                textStyle: '',
                              },
                            ],
                            direction: null,
                            format: '',
                            indent: 0,
                            type: 'tablecell',
                            version: 1,
                            backgroundColor: null,
                            colSpan: 1,
                            headerState: 0,
                            rowSpan: 1,
                            width: 103.531,
                          },
                          {
                            children: [
                              {
                                children: [
                                  {
                                    detail: 0,
                                    format: 0,
                                    mode: 'normal',
                                    style: '',
                                    text: '60-62',
                                    type: 'text',
                                    version: 1,
                                  },
                                ],
                                direction: null,
                                format: 'left',
                                indent: 0,
                                type: 'paragraph',
                                version: 1,
                                textFormat: 0,
                                textStyle: '',
                              },
                            ],
                            direction: null,
                            format: '',
                            indent: 0,
                            type: 'tablecell',
                            version: 1,
                            backgroundColor: null,
                            colSpan: 1,
                            headerState: 0,
                            rowSpan: 1,
                            width: 103.539,
                          },
                        ],
                        direction: null,
                        format: 'center',
                        indent: 0,
                        type: 'tablerow',
                        version: 1,
                      },
                    ],
                    direction: 'ltr',
                    format: '',
                    indent: 0,
                    type: 'table',
                    version: 1,
                    colWidths: [92, 92, 92, 92, 92],
                  },
                ],
                direction: 'ltr',
                format: '',
                indent: 0,
                type: 'root',
                version: 1,
              },
            },
          },
        ],
      },
    ],
    categories: categories,
    description: {
      root: {
        children: [
          {
            children: [
              {
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                text: 'Top off your look with our classic hat, crafted for style and comfort. Made with breathable, high-quality materials and an adjustable strap for the perfect fit, it’s ideal for everyday wear or outdoor adventures. Available in a range of colors to match any outfit.',
                type: 'text',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            type: 'paragraph',
            version: 1,
            textFormat: 0,
            textStyle: '',
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        type: 'root',
        version: 1,
      },
    },
    gallery: galleryImages,
    title: 'Tshirt',
    slug: 'tshirt',
    priceInUSDEnabled: true,
    priceInUSD: 4999,
    relatedProducts: relatedProducts,
  }
}

type ProductVariantArgs = {
  product: Product
  variantOptions: VariantOption[]
  inventory?: number
  priceInUSD?: number
}

export const productTshirtVariant: (
  args: ProductVariantArgs,
) => RequiredDataFromCollectionSlug<'variants'> = ({
  product,
  variantOptions,
  inventory = 492,
  priceInUSD = 4999,
}) => {
  return {
    product: product,
    options: variantOptions,
    inventory,
    priceInUSDEnabled: true,
    priceInUSD,
    _status: 'published',
  }
}
