export const slug = 'fields-relationship'

export const relationOneSlug = 'relation-one'
export const relationTrueFilterOptionSlug = 'relation-filter-true'
export const relationFalseFilterOptionSlug = 'relation-filter-false'
export const relationTwoSlug = 'relation-two'
export const relationRestrictedSlug = 'relation-restricted'
export const relationWithTitleSlug = 'relation-with-title'
export const relationUpdatedExternallySlug = 'relation-updated-externally'
export const collection1Slug = 'collection-1'
export const collection2Slug = 'collection-2'
export const versionedRelationshipFieldSlug = 'versioned-relationship-field'
