export const advancedForm = {
  id: '63c0835134d40cef85cc11a2',
  confirmationMessage: {
    root: {
      type: 'root',
      children: [
        {
          type: 'heading',
          children: [
            {
              type: 'text',
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text: 'Your shipping information submission was successful.',
              version: 1,
            },
          ],
          direction: 'ltr',
          format: '',
          indent: 0,
          tag: 'h2',
          version: 1,
        },
      ],
      direction: 'ltr',
      format: '',
      indent: 0,
      version: 1,
    },
  },
  confirmationType: 'message',
  createdAt: '2023-01-12T22:01:53.023Z',
  emails: [
    {
      id: '6644edb9cffd2c6c48a44730',
      emailFrom: '"Payload" \u003Cdemo@payloadcms.com\u003E',
      emailTo: '{{email}}',
      message: {
        root: {
          type: 'root',
          children: [
            {
              type: 'paragraph',
              children: [
                {
                  type: 'text',
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                  text: 'Your example shipping information form submission was received successfully.',
                  version: 1,
                },
              ],
              direction: 'ltr',
              format: '',
              indent: 0,
              textFormat: 0,
              version: 1,
            },
          ],
          direction: 'ltr',
          format: '',
          indent: 0,
          version: 1,
        },
      },
      subject: "You've received a new message.",
    },
  ],
  fields: [
    {
      id: '63c081b169853127a8895312',
      name: 'first-name',
      blockName: 'first-name',
      blockType: 'text',
      label: 'First Name',
      required: true,
      width: 50,
    },
    {
      id: '63c081c669853127a8895313',
      name: 'last-name',
      blockName: 'last-name',
      blockType: 'text',
      label: 'Last Name',
      required: true,
      width: 50,
    },
    {
      id: '63c081e869853127a8895314',
      name: 'email',
      blockName: 'email',
      blockType: 'email',
      label: 'Email',
      required: true,
      width: 100,
    },
    {
      id: '63c081fe69853127a8895315',
      name: 'street-address',
      blockName: 'street-address',
      blockType: 'text',
      label: 'Street Address',
      required: true,
      width: 100,
    },
    {
      id: '63c0823169853127a8895316',
      name: 'street-address-two',
      blockName: 'street-address-two',
      blockType: 'text',
      label: 'Street Address Line 2',
      width: 100,
    },
    {
      id: '63c0825a69853127a8895317',
      name: 'city',
      blockName: 'city',
      blockType: 'text',
      label: 'City',
      required: true,
      width: 50,
    },
    {
      id: '63c0826569853127a8895318',
      name: 'state',
      blockName: 'state',
      blockType: 'state',
      label: 'State',
      required: true,
      width: 50,
    },
    {
      id: '63c082bb69853127a889531a',
      name: 'zip-code',
      blockName: 'zip-code',
      blockType: 'number',
      label: 'Postal / Zip Code',
      required: true,
      width: 50,
    },
    {
      id: '63c0829269853127a8895319',
      name: 'country',
      blockName: 'country',
      blockType: 'country',
      label: 'Country',
      required: true,
      width: 50,
    },
  ],
  redirect: {},
  submitButtonLabel: 'Submit',
  title: 'Advanced Form',
  updatedAt: '2023-01-12T22:01:53.023Z',
}
