export const basicForm = {
  id: '63c0651b132c8e2783f8dcae',
  confirmationMessage: {
    root: {
      type: 'root',
      children: [
        {
          type: 'heading',
          children: [
            {
              type: 'text',
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text: 'The basic form has been submitted successfully.',
              version: 1,
            },
          ],
          direction: 'ltr',
          format: '',
          indent: 0,
          tag: 'h2',
          version: 1,
        },
      ],
      direction: 'ltr',
      format: '',
      indent: 0,
      version: 1,
    },
  },
  confirmationType: 'message',
  createdAt: '2022-12-28T20:48:53.181Z',
  emails: [
    {
      id: '6644edb9cffd2c6c48a44730',
      emailFrom: '"Payload" \u003Cdemo@payloadcms.com\u003E',
      emailTo: '{{email}}',
      message: {
        root: {
          type: 'root',
          children: [
            {
              type: 'paragraph',
              children: [
                {
                  type: 'text',
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                  text: 'Your basic form submission was successfully received.',
                  version: 1,
                },
              ],
              direction: 'ltr',
              format: '',
              indent: 0,
              textFormat: 0,
              version: 1,
            },
          ],
          direction: 'ltr',
          format: '',
          indent: 0,
          version: 1,
        },
      },
      subject: "You've received a new message.",
    },
  ],
  fields: [
    {
      id: '63adaaba5236fe69ca8973f8',
      name: 'first-name',
      blockName: 'first-name',
      blockType: 'text',
      label: 'First name',
      required: true,
      width: 50,
    },
    {
      id: '63bf4b1fd69cef4f34272f9a',
      name: 'last-name',
      blockName: 'last-name',
      blockType: 'text',
      label: 'Last name',
      required: true,
      width: 50,
    },
    {
      id: '63c0953adc1cd2c2f6c2d30b',
      name: 'email',
      blockName: 'email',
      blockType: 'email',
      label: 'Email',
      required: true,
      width: 100,
    },
    {
      id: '63adab96b65c28c168442316',
      name: 'coolest-project',
      blockName: 'coolest-project',
      blockType: 'textarea',
      label: "What's the coolest project you've built with Payload so far?",
      required: false,
      width: 100,
    },
    {
      id: '63adb90db65c28c168442322',
      blockName: 'farewell',
      blockType: 'message',
      message: {
        root: {
          type: 'root',
          children: [
            {
              type: 'paragraph',
              children: [
                {
                  type: 'text',
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                  text: 'Have a great rest of your day!',
                  version: 1,
                },
              ],
              direction: 'ltr',
              format: '',
              indent: 0,
              textFormat: 0,
              version: 1,
            },
            {
              type: 'paragraph',
              children: [
                {
                  type: 'text',
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                  text: 'Sincerely, \n\nPayload Team.',
                  version: 1,
                },
              ],
              direction: 'ltr',
              format: '',
              indent: 0,
              textFormat: 0,
              version: 1,
            },
          ],
          direction: 'ltr',
          format: '',
          indent: 0,
          version: 1,
        },
      },
    },
  ],
  redirect: {},
  submitButtonLabel: 'Submit',
  title: 'Basic Form',
  updatedAt: '2023-01-12T21:25:41.113Z',
}
