/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LexicalNodes_58262B91".
 */
export type LexicalNodes_58262B91 =
  | SerializedTextNode
  | SerializedTabNode
  | SerializedLineBreakNode
  | SerializedParagraphNode<LexicalNodes_58262B91>
  | SerializedBlockNode<MyBlock>
  | SerializedHeadingNode<LexicalNodes_58262B91>
  | {
      type: 'upload';
      /**
       * Lexical's internal serialization version for this node type.
       */
      version: number;
      [k: string]: unknown;
    }
  | SerializedQuoteNode<LexicalNodes_58262B91>
  | SerializedListNode<LexicalNodes_58262B91>
  | SerializedListItemNode<LexicalNodes_58262B91>
  | SerializedAutoLinkNode<LexicalNodes_58262B91, LexicalLinkFields_0A7E9EC0>
  | SerializedLinkNode<LexicalNodes_58262B91, LexicalLinkFields_0A7E9EC0>
  | SerializedRelationshipNode<
      | 'autosave'
      | 'pages'
      | 'posts'
      | 'server-components'
      | 'simple'
      | 'simple-with-versions'
      | 'tests'
      | 'users'
      | 'payload-kv'
      | 'payload-locked-documents'
      | 'payload-preferences'
      | 'payload-migrations'
    >;
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LexicalNodes_F229A923_Input".
 */
export type LexicalNodes_F229A923_Input =
  | SerializedTextNode
  | SerializedTabNode
  | SerializedLineBreakNode
  | SerializedParagraphNode<LexicalNodes_F229A923_Input>
  | SerializedBlockNode<MyBlock>
  | SerializedHeadingNode<LexicalNodes_F229A923_Input>
  | {
      type: 'upload';
      /**
       * Lexical's internal serialization version for this node type.
       */
      version: number;
      [k: string]: unknown;
    }
  | SerializedQuoteNode<LexicalNodes_F229A923_Input>
  | SerializedListNode<LexicalNodes_F229A923_Input>
  | SerializedListItemNode<LexicalNodes_F229A923_Input>
  | SerializedAutoLinkNode<LexicalNodes_F229A923_Input, LexicalLinkFields_0A7E9EC0>
  | SerializedLinkNode<LexicalNodes_F229A923_Input, LexicalLinkFields_0A7E9EC0>
  | SerializedRelationshipNodeInput<
      | 'autosave'
      | 'pages'
      | 'posts'
      | 'server-components'
      | 'simple'
      | 'simple-with-versions'
      | 'tests'
      | 'users'
      | 'payload-mcp-api-keys'
      | 'payload-kv'
      | 'payload-locked-documents'
      | 'payload-preferences'
      | 'payload-migrations'
    >;

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    autosave: Autosave;
    pages: Page;
    posts: Post;
    'server-components': ServerComponent;
    simple: Simple;
    'simple-with-versions': SimpleWithVersion;
    tests: Test;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    autosave: AutosaveSelect<false> | AutosaveSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    'server-components': ServerComponentsSelect<false> | ServerComponentsSelect<true>;
    simple: SimpleSelect<false> | SimpleSelect<true>;
    'simple-with-versions': SimpleWithVersionsSelect<false> | SimpleWithVersionsSelect<true>;
    tests: TestsSelect<false> | TestsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    admin: Admin;
    'autosave-global': AutosaveGlobal;
    'global-with-versions': GlobalWithVersion;
    menu: Menu;
  };
  globalsSelect: {
    admin: AdminSelect<false> | AdminSelect<true>;
    'autosave-global': AutosaveGlobalSelect<false> | AutosaveGlobalSelect<true>;
    'global-with-versions': GlobalWithVersionsSelect<false> | GlobalWithVersionsSelect<true>;
    menu: MenuSelect<false> | MenuSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  collectionsInput: {
    autosave: AutosaveInput;
    pages: PageInput;
    posts: PostInput;
    'server-components': ServerComponentInput;
    simple: SimpleInput;
    'simple-with-versions': SimpleWithVersionInput;
    tests: TestInput;
    users: UserInput;
    'payload-mcp-api-keys': PayloadMcpApiKeyInput;
    'payload-kv': PayloadKvInput;
    'payload-locked-documents': PayloadLockedDocumentInput;
    'payload-preferences': PayloadPreferenceInput;
    'payload-migrations': PayloadMigrationInput;
  };
  globalsInput: {
    admin: AdminInput;
    'autosave-global': AutosaveGlobalInput;
    'global-with-versions': GlobalWithVersionInput;
    menu: MenuInput;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "autosave".
 */
export interface Autosave {
  id: string;
  fieldA?: string | null;
  fieldB?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  text?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: string;
  text?: string | null;
  richText?: LexicalRichText<LexicalNodes_58262B91> | null;
  documentLoaded?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "server-components".
 */
export interface ServerComponent {
  id: string;
  customTextServer?: string | null;
  richText?: LexicalRichText<LexicalNodes_58262B91> | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "simple".
 */
export interface Simple {
  id: string;
  fieldA?: string | null;
  fieldB?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "simple-with-versions".
 */
export interface SimpleWithVersion {
  id: string;
  fieldA?: string | null;
  fieldB?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tests".
 */
export interface Test {
  id: string;
  text?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string | null;
  roles?: ('is_user' | 'is_admin')[] | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'autosave';
        value: string | Autosave;
      } | null)
    | ({
        relationTo: 'posts';
        value: string | Post;
      } | null)
    | ({
        relationTo: 'server-components';
        value: string | ServerComponent;
      } | null)
    | ({
        relationTo: 'simple';
        value: string | Simple;
      } | null)
    | ({
        relationTo: 'simple-with-versions';
        value: string | SimpleWithVersion;
      } | null)
    | ({
        relationTo: 'tests';
        value: string | Test;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "autosave_select".
 */
export interface AutosaveSelect<T extends boolean = true> {
  fieldA?: T;
  fieldB?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  text?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  text?: T;
  richText?: T;
  documentLoaded?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "server-components_select".
 */
export interface ServerComponentsSelect<T extends boolean = true> {
  customTextServer?: T;
  richText?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "simple_select".
 */
export interface SimpleSelect<T extends boolean = true> {
  fieldA?: T;
  fieldB?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "simple-with-versions_select".
 */
export interface SimpleWithVersionsSelect<T extends boolean = true> {
  fieldA?: T;
  fieldB?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tests_select".
 */
export interface TestsSelect<T extends boolean = true> {
  text?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admin".
 */
export interface Admin {
  id: string;
  adminText?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "autosave-global".
 */
export interface AutosaveGlobal {
  id: string;
  text?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "global-with-versions".
 */
export interface GlobalWithVersion {
  id: string;
  text?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu".
 */
export interface Menu {
  id: string;
  globalText?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admin_select".
 */
export interface AdminSelect<T extends boolean = true> {
  adminText?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "autosave-global_select".
 */
export interface AutosaveGlobalSelect<T extends boolean = true> {
  text?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "global-with-versions_select".
 */
export interface GlobalWithVersionsSelect<T extends boolean = true> {
  text?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu_select".
 */
export interface MenuSelect<T extends boolean = true> {
  globalText?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "autosave_input".
 */
export interface AutosaveInput {
  id?: string;
  fieldA?: string | null;
  fieldB?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_input".
 */
export interface PageInput {
  id?: string;
  text?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_input".
 */
export interface PostInput {
  id?: string;
  text?: string | null;
  richText?: LexicalRichText<LexicalNodes_F229A923_Input> | null;
  documentLoaded?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "server-components_input".
 */
export interface ServerComponentInput {
  id?: string;
  customTextServer?: string | null;
  richText?: LexicalRichText<LexicalNodes_F229A923_Input> | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "simple_input".
 */
export interface SimpleInput {
  id?: string;
  fieldA?: string | null;
  fieldB?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "simple-with-versions_input".
 */
export interface SimpleWithVersionInput {
  id?: string;
  fieldA?: string | null;
  fieldB?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tests_input".
 */
export interface TestInput {
  id?: string;
  text?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_input".
 */
export interface UserInput {
  id?: string;
  name?: string | null;
  roles?: ('is_user' | 'is_admin')[] | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys_input".
 */
export interface PayloadMcpApiKeyInput {
  id?: string;
  apiKey: string;
  apiKeyIndex: string;
  access?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  label?: string | null;
  description?: string | null;
  lastUsed?: string | null;
  user: string;
  overrideAccess?: boolean | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_input".
 */
export interface PayloadKvInput {
  id?: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_input".
 */
export interface PayloadLockedDocumentInput {
  id?: string;
  document?:
    | ({
        relationTo: 'autosave';
        value: string;
      } | null)
    | ({
        relationTo: 'posts';
        value: string;
      } | null)
    | ({
        relationTo: 'server-components';
        value: string;
      } | null)
    | ({
        relationTo: 'simple';
        value: string;
      } | null)
    | ({
        relationTo: 'simple-with-versions';
        value: string;
      } | null)
    | ({
        relationTo: 'tests';
        value: string;
      } | null)
    | ({
        relationTo: 'users';
        value: string;
      } | null)
    | ({
        relationTo: 'payload-mcp-api-keys';
        value: string;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_input".
 */
export interface PayloadPreferenceInput {
  id?: string;
  user: {
    relationTo: 'users';
    value: string;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_input".
 */
export interface PayloadMigrationInput {
  id?: string;
  name?: string | null;
  batch?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admin_input".
 */
export interface AdminInput {
  id?: string;
  adminText?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "autosave-global_input".
 */
export interface AutosaveGlobalInput {
  id?: string;
  text?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "global-with-versions_input".
 */
export interface GlobalWithVersionInput {
  id?: string;
  text?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu_input".
 */
export interface MenuInput {
  id?: string;
  globalText?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MyBlock".
 */
export interface MyBlock {
  id: string;
  blockType: 'myBlock';
  someText?: string | null;
  someTextRequired: string;
  radios?: ('option1' | 'option2' | 'option3') | null;
  blockName?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LexicalLinkFields_0A7E9EC0".
 */
export interface LexicalLinkFields_0A7E9EC0 {
  linkType: 'custom' | 'internal';
  url?: string;
  doc?: {
    relationTo: string;
    value:
      | string
      | number
      | {
          id: string | number;
          [k: string]: unknown;
        };
  } | null;
  newTab: boolean;
  description?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}

/** @internal Core Lexical types — see @payloadcms/richtext-lexical. */
export type LexicalElementFormat = 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
export type LexicalElementDirection = ('ltr' | 'rtl') | null;

export interface SerializedLexicalElementBase<TChildren> {
  children: TChildren[];
  direction: LexicalElementDirection;
  format: LexicalElementFormat;
  indent: number;
  textFormat?: number;
  textStyle?: string;
  version: number;
}

export type LexicalTextMode = 'normal' | 'token' | 'segmented';

export interface SerializedTextNode {
  type: 'text';
  detail: number;
  format: number;
  mode: LexicalTextMode;
  style: string;
  text: string;
  version: number;
}

export interface SerializedTabNode {
  type: 'tab';
  detail: number;
  format: number;
  mode: LexicalTextMode;
  style: string;
  text: string;
  version: number;
}

export interface SerializedLineBreakNode {
  type: 'linebreak';
  version: number;
}

export interface SerializedParagraphNode<TChildren> extends SerializedLexicalElementBase<TChildren> {
  type: 'paragraph';
  textFormat: number;
  textStyle: string;
}

export type SerializedBlockNode<TFields extends { blockType: string }> = TFields extends unknown ? {
  type: 'block';
  format: LexicalElementFormat;
  version: number;
  fields: { id: string; blockName?: string | null } & Omit<TFields, 'id' | 'blockName'>;
} : never;
export type SerializedInlineBlockNode<TFields extends { blockType: string }> = TFields extends unknown ? {
  type: 'inlineBlock';
  version: number;
  fields: { id: string } & Omit<TFields, 'id'>;
} : never;

export interface SerializedHeadingNode<
  TChildren,
  TTag extends 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' = 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6',
> extends SerializedLexicalElementBase<TChildren> {
  type: 'heading';
  tag: TTag;
}

export type SerializedUploadNode<TSlugs extends keyof Config['collections'], TFields = { [k: string]: unknown }> = {
  type: 'upload';
  format: LexicalElementFormat;
  id: string;
  version: number;
  fields: TFields;
} & {
  [TSlug in TSlugs]: {
    relationTo: TSlug;
    value: Config['collections'][TSlug]['id'] | Config['collections'][TSlug];
  };
}[TSlugs];

export interface SerializedQuoteNode<TChildren> extends SerializedLexicalElementBase<TChildren> {
  type: 'quote';
}

export interface SerializedListNode<TChildren> extends SerializedLexicalElementBase<TChildren> {
  type: 'list';
  checked?: boolean;
  listType: 'number' | 'bullet' | 'check';
  start: number;
  tag: 'ul' | 'ol';
}

export interface SerializedListItemNode<TChildren> extends SerializedLexicalElementBase<TChildren> {
  type: 'listitem';
  checked?: boolean;
  value: number;
}

export interface LexicalLinkFields {
  [k: string]: unknown;
  doc?: {
    relationTo: string;
    value: Config['db']['defaultIDType'] | { [k: string]: unknown; id: Config['db']['defaultIDType'] };
  } | null;
  linkType: 'custom' | 'internal';
  newTab: boolean;
  url?: string;
}
export interface SerializedLinkNode<TChildren, TFields = LexicalLinkFields> extends SerializedLexicalElementBase<TChildren> {
  type: 'link';
  fields: TFields;
  id?: string;
}
export interface SerializedAutoLinkNode<TChildren, TFields = LexicalLinkFields> extends SerializedLexicalElementBase<TChildren> {
  type: 'autolink';
  fields: TFields;
}

export type SerializedRelationshipNode<TSlugs extends keyof Config['collections']> = {
  type: 'relationship';
  format: LexicalElementFormat;
  version: number;
} & {
  [TSlug in TSlugs]: {
    relationTo: TSlug;
    value: Config['collections'][TSlug]['id'] | Config['collections'][TSlug];
  };
}[TSlugs];

/** Shape of a Lexical `richText` field. */
export interface LexicalRichText<TNode> {
  root: {
    children: TNode[];
    direction: LexicalElementDirection;
    format: LexicalElementFormat;
    indent: number;
    type: 'root';
    version: number;
  };
}

export type SerializedUploadNodeInput<TSlugs extends keyof Config['collections'], TFields = { [k: string]: unknown }> = {
  type: 'upload';
  format: LexicalElementFormat;
  id: string;
  version: number;
  fields: TFields;
} & {
  [TSlug in TSlugs]: {
    relationTo: TSlug;
    value: Config['collections'][TSlug]['id'];
  };
}[TSlugs];

export type SerializedRelationshipNodeInput<TSlugs extends keyof Config['collections']> = {
  type: 'relationship';
  format: LexicalElementFormat;
  version: number;
} & {
  [TSlug in TSlugs]: {
    relationTo: TSlug;
    value: Config['collections'][TSlug]['id'];
  };
}[TSlugs];


declare module 'payload' {
  // @ts-ignore 
  export interface GeneratedTypes extends Config {}
}