export const mediaSlug = 'media'
export const mediaWithPrefixSlug = 'media-with-prefix'
export const mediaWithCustomURLSlug = 'media-with-custom-url'
export const mediaWithGenerateFileURLSlug = 'media-with-generate-file-url'
export const restrictedMediaSlug = 'restricted-media'
export const testMetadataSlug = 'test-metadata'
export const mediaWithBasePrefixSlug = 'media-with-base-prefix'
export const mediaWithBasePrefixAndCollectionPrefixSlug =
  'media-with-base-prefix-and-collection-prefix'
export const prefix = 'test-prefix'
export const basePrefix = 'base-test'
export const collectionPrefix = 'collection-level'
