export const mediaSlug = 'media'
export const mediaWithPrefixSlug = 'media-with-prefix'
export const mediaWithCustomURLSlug = 'media-with-custom-url'
export const restrictedMediaSlug = 'restricted-media'
export const testMetadataSlug = 'test-metadata'
export const prefix = 'test-prefix'
