/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LexicalNodes_6C4CCB8D".
 */
export type LexicalNodes_6C4CCB8D =
  | SerializedTextNode
  | SerializedTabNode
  | SerializedLineBreakNode
  | SerializedParagraphNode<LexicalNodes_6C4CCB8D>
  | SerializedAutoLinkNode<LexicalNodes_6C4CCB8D, LexicalLinkFields_6C4CCB8D>
  | SerializedLinkNode<LexicalNodes_6C4CCB8D, LexicalLinkFields_6C4CCB8D>
  | SerializedBlockNode<NestedBlock>
  | SerializedInlineBlockNode<{blockType: string}>
  | SerializedHorizontalRuleNode
  | {
      type: 'upload';
      /**
       * Lexical's internal serialization version for this node type.
       */
      version: number;
      [k: string]: unknown;
    }
  | SerializedQuoteNode<LexicalNodes_6C4CCB8D>
  | SerializedRelationshipNode<
      | 'beforeOperation'
      | 'before-change-hooks'
      | 'before-validate'
      | 'afterOperation'
      | 'context-hooks'
      | 'transforms'
      | 'hooks'
      | 'nested-after-read-hooks'
      | 'nested-after-change-hooks'
      | 'chaining-hooks'
      | 'relations'
      | 'hooks-users'
      | 'data-hooks'
      | 'before-delete-hooks'
      | 'before-delete-2-hooks'
      | 'value-hooks'
      | 'after-read'
      | 'override-access-hooks'
      | 'payload-mcp-api-keys'
      | 'payload-kv'
      | 'payload-locked-documents'
      | 'payload-preferences'
      | 'payload-migrations'
    >
  | SerializedListNode<LexicalNodes_6C4CCB8D>
  | SerializedListItemNode<LexicalNodes_6C4CCB8D>
  | SerializedHeadingNode<LexicalNodes_6C4CCB8D>;

export interface Config {
  auth: {
    'hooks-users': HooksUserAuthOperations;
    'payload-mcp-api-keys': PayloadMcpApiKeyAuthOperations;
  };
  blocks: {};
  collections: {
    beforeOperation: BeforeOperation;
    'before-change-hooks': BeforeChangeHook;
    'before-validate': BeforeValidate;
    afterOperation: AfterOperation;
    'context-hooks': ContextHook;
    transforms: Transform;
    hooks: Hook;
    'nested-after-read-hooks': NestedAfterReadHook;
    'nested-after-change-hooks': NestedAfterChangeHook;
    'chaining-hooks': ChainingHook;
    relations: Relation;
    'hooks-users': HooksUser;
    'data-hooks': DataHook;
    'before-delete-hooks': BeforeDeleteHook;
    'before-delete-2-hooks': BeforeDelete2Hook;
    'value-hooks': ValueHook;
    'after-read': AfterRead;
    'override-access-hooks': OverrideAccessHook;
    'payload-mcp-api-keys': PayloadMcpApiKey;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    beforeOperation: BeforeOperationSelect<false> | BeforeOperationSelect<true>;
    'before-change-hooks': BeforeChangeHooksSelect<false> | BeforeChangeHooksSelect<true>;
    'before-validate': BeforeValidateSelect<false> | BeforeValidateSelect<true>;
    afterOperation: AfterOperationSelect<false> | AfterOperationSelect<true>;
    'context-hooks': ContextHooksSelect<false> | ContextHooksSelect<true>;
    transforms: TransformsSelect<false> | TransformsSelect<true>;
    hooks: HooksSelect<false> | HooksSelect<true>;
    'nested-after-read-hooks': NestedAfterReadHooksSelect<false> | NestedAfterReadHooksSelect<true>;
    'nested-after-change-hooks': NestedAfterChangeHooksSelect<false> | NestedAfterChangeHooksSelect<true>;
    'chaining-hooks': ChainingHooksSelect<false> | ChainingHooksSelect<true>;
    relations: RelationsSelect<false> | RelationsSelect<true>;
    'hooks-users': HooksUsersSelect<false> | HooksUsersSelect<true>;
    'data-hooks': DataHooksSelect<false> | DataHooksSelect<true>;
    'before-delete-hooks': BeforeDeleteHooksSelect<false> | BeforeDeleteHooksSelect<true>;
    'before-delete-2-hooks': BeforeDelete2HooksSelect<false> | BeforeDelete2HooksSelect<true>;
    'value-hooks': ValueHooksSelect<false> | ValueHooksSelect<true>;
    'after-read': AfterReadSelect<false> | AfterReadSelect<true>;
    'override-access-hooks': OverrideAccessHooksSelect<false> | OverrideAccessHooksSelect<true>;
    'payload-mcp-api-keys': PayloadMcpApiKeysSelect<false> | PayloadMcpApiKeysSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    'data-hooks-global': DataHooksGlobal;
  };
  globalsSelect: {
    'data-hooks-global': DataHooksGlobalSelect<false> | DataHooksGlobalSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: HooksUser | PayloadMcpApiKey;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface HooksUserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface PayloadMcpApiKeyAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "beforeOperation".
 */
export interface BeforeOperation {
  id: string;
  category?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "before-change-hooks".
 */
export interface BeforeChangeHook {
  id: string;
  title: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "before-validate".
 */
export interface BeforeValidate {
  id: string;
  title?: string | null;
  selection?: ('a' | 'b') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "afterOperation".
 */
export interface AfterOperation {
  id: string;
  title: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "context-hooks".
 */
export interface ContextHook {
  id: string;
  value?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transforms".
 */
export interface Transform {
  id: string;
  /**
   * @minItems 2
   * @maxItems 2
   */
  transform?: [number, number] | null;
  /**
   * @minItems 2
   * @maxItems 2
   */
  localizedTransform?: [number, number] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hooks".
 */
export interface Hook {
  id: string;
  fieldBeforeValidate?: boolean | null;
  fieldBeforeChange?: boolean | null;
  fieldAfterChange?: boolean | null;
  fieldAfterRead?: boolean | null;
  collectionBeforeValidate?: boolean | null;
  collectionBeforeChange?: boolean | null;
  collectionAfterChange?: boolean | null;
  collectionBeforeRead?: boolean | null;
  collectionAfterRead?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nested-after-read-hooks".
 */
export interface NestedAfterReadHook {
  id: string;
  text?: string | null;
  group?: {
    array?:
      | {
          input?: string | null;
          afterRead?: string | null;
          shouldPopulate?: (string | null) | Relation;
          id?: string | null;
        }[]
      | null;
    subGroup?: {
      afterRead?: string | null;
      shouldPopulate?: (string | null) | Relation;
    };
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "relations".
 */
export interface Relation {
  id: string;
  title: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nested-after-change-hooks".
 */
export interface NestedAfterChangeHook {
  id: string;
  text?: string | null;
  group?: {
    array?:
      | {
          nestedAfterChange?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  lexical?: LexicalRichText<LexicalNodes_6C4CCB8D> | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chaining-hooks".
 */
export interface ChainingHook {
  id: string;
  text?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hooks-users".
 */
export interface HooksUser {
  id: string;
  roles: ('admin' | 'user')[];
  afterLoginHook?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'hooks-users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "data-hooks".
 */
export interface DataHook {
  id: string;
  field_collectionAndField?: string | null;
  collection_beforeOperation_collection?: string | null;
  collection_beforeChange_collection?: string | null;
  collection_afterChange_collection?: string | null;
  collection_beforeRead_collection?: string | null;
  collection_afterRead_collection?: string | null;
  collection_afterOperation_collection?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "before-delete-hooks".
 */
export interface BeforeDeleteHook {
  id: string;
  title?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "before-delete-2-hooks".
 */
export interface BeforeDelete2Hook {
  id: string;
  title?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "value-hooks".
 */
export interface ValueHook {
  id: string;
  slug?: string | null;
  beforeValidate_value?: string | null;
  beforeChange_value?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "after-read".
 */
export interface AfterRead {
  id: string;
  title?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "override-access-hooks".
 */
export interface OverrideAccessHook {
  id: string;
  title?: string | null;
  beforeReadCalled?: boolean | null;
  beforeReadOverrideAccess?: boolean | null;
  afterReadCalled?: boolean | null;
  afterReadOverrideAccess?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * API keys control which collections, resources, tools, and prompts MCP clients can access
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys".
 */
export interface PayloadMcpApiKey {
  id: string;
  /**
   * The user that the API key is associated with.
   */
  user: string | HooksUser;
  /**
   * A useful label for the API key.
   */
  label?: string | null;
  /**
   * The purpose of the API key.
   */
  description?: string | null;
  /**
   * When checked, this key bypasses Payload access control on every operation it performs. Leave unchecked unless you have a specific reason.
   */
  overrideAccess?: boolean | null;
  /**
   * Access for this API key — uncheck to revoke individual tools.
   */
  access?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  collection: 'payload-mcp-api-keys';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'beforeOperation';
        value: string | BeforeOperation;
      } | null)
    | ({
        relationTo: 'before-change-hooks';
        value: string | BeforeChangeHook;
      } | null)
    | ({
        relationTo: 'before-validate';
        value: string | BeforeValidate;
      } | null)
    | ({
        relationTo: 'afterOperation';
        value: string | AfterOperation;
      } | null)
    | ({
        relationTo: 'context-hooks';
        value: string | ContextHook;
      } | null)
    | ({
        relationTo: 'transforms';
        value: string | Transform;
      } | null)
    | ({
        relationTo: 'hooks';
        value: string | Hook;
      } | null)
    | ({
        relationTo: 'nested-after-read-hooks';
        value: string | NestedAfterReadHook;
      } | null)
    | ({
        relationTo: 'nested-after-change-hooks';
        value: string | NestedAfterChangeHook;
      } | null)
    | ({
        relationTo: 'chaining-hooks';
        value: string | ChainingHook;
      } | null)
    | ({
        relationTo: 'relations';
        value: string | Relation;
      } | null)
    | ({
        relationTo: 'hooks-users';
        value: string | HooksUser;
      } | null)
    | ({
        relationTo: 'data-hooks';
        value: string | DataHook;
      } | null)
    | ({
        relationTo: 'before-delete-hooks';
        value: string | BeforeDeleteHook;
      } | null)
    | ({
        relationTo: 'before-delete-2-hooks';
        value: string | BeforeDelete2Hook;
      } | null)
    | ({
        relationTo: 'value-hooks';
        value: string | ValueHook;
      } | null)
    | ({
        relationTo: 'after-read';
        value: string | AfterRead;
      } | null)
    | ({
        relationTo: 'override-access-hooks';
        value: string | OverrideAccessHook;
      } | null)
    | ({
        relationTo: 'payload-mcp-api-keys';
        value: string | PayloadMcpApiKey;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'hooks-users';
        value: string | HooksUser;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: string | PayloadMcpApiKey;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user:
    | {
        relationTo: 'hooks-users';
        value: string | HooksUser;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: string | PayloadMcpApiKey;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "beforeOperation_select".
 */
export interface BeforeOperationSelect<T extends boolean = true> {
  category?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "before-change-hooks_select".
 */
export interface BeforeChangeHooksSelect<T extends boolean = true> {
  title?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "before-validate_select".
 */
export interface BeforeValidateSelect<T extends boolean = true> {
  title?: T;
  selection?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "afterOperation_select".
 */
export interface AfterOperationSelect<T extends boolean = true> {
  title?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "context-hooks_select".
 */
export interface ContextHooksSelect<T extends boolean = true> {
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transforms_select".
 */
export interface TransformsSelect<T extends boolean = true> {
  transform?: T;
  localizedTransform?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hooks_select".
 */
export interface HooksSelect<T extends boolean = true> {
  fieldBeforeValidate?: T;
  fieldBeforeChange?: T;
  fieldAfterChange?: T;
  fieldAfterRead?: T;
  collectionBeforeValidate?: T;
  collectionBeforeChange?: T;
  collectionAfterChange?: T;
  collectionBeforeRead?: T;
  collectionAfterRead?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nested-after-read-hooks_select".
 */
export interface NestedAfterReadHooksSelect<T extends boolean = true> {
  text?: T;
  group?:
    | T
    | {
        array?:
          | T
          | {
              input?: T;
              afterRead?: T;
              shouldPopulate?: T;
              id?: T;
            };
        subGroup?:
          | T
          | {
              afterRead?: T;
              shouldPopulate?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nested-after-change-hooks_select".
 */
export interface NestedAfterChangeHooksSelect<T extends boolean = true> {
  text?: T;
  group?:
    | T
    | {
        array?:
          | T
          | {
              nestedAfterChange?: T;
              id?: T;
            };
      };
  lexical?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chaining-hooks_select".
 */
export interface ChainingHooksSelect<T extends boolean = true> {
  text?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "relations_select".
 */
export interface RelationsSelect<T extends boolean = true> {
  title?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hooks-users_select".
 */
export interface HooksUsersSelect<T extends boolean = true> {
  roles?: T;
  afterLoginHook?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "data-hooks_select".
 */
export interface DataHooksSelect<T extends boolean = true> {
  field_collectionAndField?: T;
  collection_beforeOperation_collection?: T;
  collection_beforeChange_collection?: T;
  collection_afterChange_collection?: T;
  collection_beforeRead_collection?: T;
  collection_afterRead_collection?: T;
  collection_afterOperation_collection?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "before-delete-hooks_select".
 */
export interface BeforeDeleteHooksSelect<T extends boolean = true> {
  title?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "before-delete-2-hooks_select".
 */
export interface BeforeDelete2HooksSelect<T extends boolean = true> {
  title?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "value-hooks_select".
 */
export interface ValueHooksSelect<T extends boolean = true> {
  slug?: T;
  beforeValidate_value?: T;
  beforeChange_value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "after-read_select".
 */
export interface AfterReadSelect<T extends boolean = true> {
  title?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "override-access-hooks_select".
 */
export interface OverrideAccessHooksSelect<T extends boolean = true> {
  title?: T;
  beforeReadCalled?: T;
  beforeReadOverrideAccess?: T;
  afterReadCalled?: T;
  afterReadOverrideAccess?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys_select".
 */
export interface PayloadMcpApiKeysSelect<T extends boolean = true> {
  user?: T;
  label?: T;
  description?: T;
  overrideAccess?: T;
  access?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "data-hooks-global".
 */
export interface DataHooksGlobal {
  id: string;
  field_globalAndField?: string | null;
  global_beforeChange_global?: string | null;
  global_afterChange_global?: string | null;
  global_beforeRead_global?: string | null;
  global_afterRead_global?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "data-hooks-global_select".
 */
export interface DataHooksGlobalSelect<T extends boolean = true> {
  field_globalAndField?: T;
  global_beforeChange_global?: T;
  global_afterChange_global?: T;
  global_beforeRead_global?: T;
  global_afterRead_global?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NestedLinkBlock".
 */
export interface NestedLinkBlock {
  nestedRelationship?: (string | null) | Relation;
  id?: string | null;
  blockName?: string | null;
  blockType: 'nestedLinkBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NestedBlock".
 */
export interface NestedBlock {
  id: string;
  blockType: 'nestedBlock';
  nestedAfterChange?: string | null;
  blockName?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LexicalLinkFields_6C4CCB8D".
 */
export interface LexicalLinkFields_6C4CCB8D {
  linkBlocks?: NestedLinkBlock[] | null;
  doc?: {
    relationTo: string;
    value:
      | string
      | number
      | {
          id: string | number;
          [k: string]: unknown;
        };
  } | null;
  linkType: 'custom' | 'internal';
  newTab: boolean;
  url?: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}

/** @internal Core Lexical types — see @payloadcms/richtext-lexical. */
export type LexicalElementFormat = 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
export type LexicalElementDirection = ('ltr' | 'rtl') | null;

export interface SerializedLexicalElementBase<TChildren> {
  children: TChildren[];
  direction: LexicalElementDirection;
  format: LexicalElementFormat;
  indent: number;
  textFormat?: number;
  textStyle?: string;
  version: number;
}

export type LexicalTextMode = 'normal' | 'token' | 'segmented';

export interface SerializedTextNode {
  type: 'text';
  detail: number;
  format: number;
  mode: LexicalTextMode;
  style: string;
  text: string;
  version: number;
}

export interface SerializedTabNode {
  type: 'tab';
  detail: number;
  format: number;
  mode: LexicalTextMode;
  style: string;
  text: string;
  version: number;
}

export interface SerializedLineBreakNode {
  type: 'linebreak';
  version: number;
}

export interface SerializedParagraphNode<TChildren> extends SerializedLexicalElementBase<TChildren> {
  type: 'paragraph';
  textFormat: number;
  textStyle: string;
}

export interface LexicalLinkFields {
  [k: string]: unknown;
  doc?: {
    relationTo: string;
    value: Config['db']['defaultIDType'] | { [k: string]: unknown; id: Config['db']['defaultIDType'] };
  } | null;
  linkType: 'custom' | 'internal';
  newTab: boolean;
  url?: string;
}
export interface SerializedLinkNode<TChildren, TFields = LexicalLinkFields> extends SerializedLexicalElementBase<TChildren> {
  type: 'link';
  fields: TFields;
  id?: string;
}
export interface SerializedAutoLinkNode<TChildren, TFields = LexicalLinkFields> extends SerializedLexicalElementBase<TChildren> {
  type: 'autolink';
  fields: TFields;
}

export type SerializedBlockNode<TFields extends { blockType: string }> = {
  type: 'block';
  format: LexicalElementFormat;
  version: number;
  fields: { id: string; blockName?: string | null } & Omit<TFields, 'id' | 'blockName'>;
};
export type SerializedInlineBlockNode<TFields extends { blockType: string }> = {
  type: 'inlineBlock';
  version: number;
  fields: { id: string } & Omit<TFields, 'id'>;
};

export interface SerializedHorizontalRuleNode {
  type: 'horizontalrule';
  version: number;
}

export type SerializedUploadNode<TSlugs extends keyof Config['collections'], TFields = { [k: string]: unknown }> = {
  type: 'upload';
  format: LexicalElementFormat;
  id: string;
  version: number;
  fields: TFields;
} & {
  [TSlug in TSlugs]: {
    relationTo: TSlug;
    value: number | string | Config['collections'][TSlug];
  };
}[TSlugs];

export interface SerializedQuoteNode<TChildren> extends SerializedLexicalElementBase<TChildren> {
  type: 'quote';
}

export type SerializedRelationshipNode<TSlugs extends keyof Config['collections']> = {
  type: 'relationship';
  format: LexicalElementFormat;
  version: number;
} & {
  [TSlug in TSlugs]: {
    relationTo: TSlug;
    value: number | string | Config['collections'][TSlug];
  };
}[TSlugs];

export interface SerializedListNode<TChildren> extends SerializedLexicalElementBase<TChildren> {
  type: 'list';
  checked?: boolean;
  listType: 'number' | 'bullet' | 'check';
  start: number;
  tag: 'ul' | 'ol';
}

export interface SerializedListItemNode<TChildren> extends SerializedLexicalElementBase<TChildren> {
  type: 'listitem';
  checked?: boolean;
  value: number;
}

export interface SerializedHeadingNode<
  TChildren,
  TTag extends 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' = 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6',
> extends SerializedLexicalElementBase<TChildren> {
  type: 'heading';
  tag: TTag;
}

/** Shape of a Lexical `richText` field. */
export interface LexicalRichText<TNode> {
  root: {
    children: TNode[];
    direction: LexicalElementDirection;
    format: LexicalElementFormat;
    indent: number;
    type: 'root';
    version: number;
  };
}


declare module 'payload' {
  // @ts-ignore 
  export interface GeneratedTypes extends Config {}
}