name: lock-issues

on:
  schedule:
    # Run nightly at 12am EST, staggered with stale workflow
    - cron: '0 5 * * *'
  workflow_dispatch:

permissions:
  issues: write

jobs:
  lock_issues:
    runs-on: ubuntu-24.04
    steps:
      - name: Lock issues
        uses: dessant/lock-threads@7266a7ce5c1df01b1c6db85bf8cd86c737dadbe7 # v6.0.0
        with:
          process-only: 'issues'
          issue-inactive-days: '7'
          exclude-any-issue-labels: 'status: awaiting-reply'
          log-output: true
          issue-comment: >
            This issue has been automatically locked.

            Please open a new issue if this issue persists with any additional detail.
