name: stale

on:
  schedule:
    # Run nightly at 1am EST, staggered with lock-issues workflow
    - cron: '0 6 * * *'

  workflow_dispatch:
    inputs:
      dry-run:
        description: Run the stale action in debug-only mode
        default: false
        required: false
        type: boolean

jobs:
  stale:
    runs-on: ubuntu-24.04
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v9
        id: stale
        with:
          debug-only: ${{ inputs.dry-run || false }}

          days-before-stale: 30
          days-before-close: -1 # Disable closing
          ascending: true
          operations-per-run: 300
          exempt-all-assignees: true

          # Issues
          stale-issue-label: stale
          exempt-issue-labels: 'prioritized,keep,created-by: Payload team,created-by: Contributor,status: verified'
          stale-issue-message: ''

          close-issue-message: |
            This issue was automatically closed due to lack of activity.

          # Pull Requests
          stale-pr-label: stale
          exempt-pr-labels: 'prioritized,keep,created-by: Payload team,created-by: Contributor'
          stale-pr-message: ''
          close-pr-message: |
            This pull request was automatically closed due to lack of activity.

      # TODO: Add a step to notify team
      - name: Print outputs
        run: echo ${{ format('{0},{1}', toJSON(steps.stale.outputs.staled-issues-prs), toJSON(steps.stale.outputs.closed-issues-prs)) }}
