export { DefaultAccount } from '../views/Account'
export { DefaultDashboard } from '../views/Dashboard'
export { DefaultList } from '../views/List'
export { DefaultEdit } from '../views/Edit'
export type { DefaultEditViewProps } from '../views/Edit/types'
export type { DefaultAccountViewProps } from '../views/Account/types'
