import {
  ACTION_ITEM,
  BLOCKQUOTE,
  CODE_BLOCK,
  HeadingType,
  IMAGE,
  LINK,
  ListType,
  MARK_BOLD,
  MARK_CODE,
  MARK_HIGHLIGHT,
  MARK_ITALIC,
  MARK_SEARCH_HIGHLIGHT,
  MARK_STRIKETHROUGH,
  MARK_SUBSCRIPT,
  MARK_SUPERSCRIPT,
  MARK_UNDERLINE,
  MEDIA_EMBED,
  MENTION,
  PARAGRAPH,
  TableType,
} from '@udecode/slate-plugins';

export const headingTypes = [
  HeadingType.H1,
  HeadingType.H2,
  HeadingType.H3,
  HeadingType.H4,
  HeadingType.H5,
  HeadingType.H6,
];

export const nodeTypes = {
  // elements
  typeP: PARAGRAPH,
  typeMention: MENTION,
  typeBlockquote: BLOCKQUOTE,
  typeCodeBlock: CODE_BLOCK,
  typeLink: LINK,
  typeImg: IMAGE,
  typeMediaEmbed: MEDIA_EMBED,
  typeActionItem: ACTION_ITEM,
  typeTable: TableType.TABLE,
  typeTr: TableType.ROW,
  typeTd: TableType.CELL,
  typeUl: ListType.UL,
  typeOl: ListType.OL,
  typeLi: ListType.LI,
  typeH1: HeadingType.H1,
  typeH2: HeadingType.H2,
  typeH3: HeadingType.H3,
  typeH4: HeadingType.H4,
  typeH5: HeadingType.H5,
  typeH6: HeadingType.H6,
  // marks
  typeBold: MARK_BOLD,
  typeItalic: MARK_ITALIC,
  typeUnderline: MARK_UNDERLINE,
  typeStrikethrough: MARK_STRIKETHROUGH,
  typeCode: MARK_CODE,
  typeSubscript: MARK_SUBSCRIPT,
  typeSuperscript: MARK_SUPERSCRIPT,
  typeHighlight: MARK_HIGHLIGHT,
  typeSearchHighlight: MARK_SEARCH_HIGHLIGHT,
};
